name: online_boutique
description: FTL Online Boutique

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  flutter_hooks: ^0.20.3
  google_fonts: 6.1.0
  hooks_riverpod: ^2.4.4
  http: ^1.1.0
  intl: ^0.18.1
  riverpod: ^2.4.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/
