apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftl-controller
  labels:
    app: ftl-controller
spec:
  selector:
    matchLabels:
      app: ftl-controller
  template:
    metadata:
      labels:
        app: ftl-controller
    spec:
      containers:
        - name: app
          image: ftl-controller
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FTL_CONTROLLER_DSN
              value: "postgres://ftl-pg-cluster/ftl?sslmode=disable&user=postgres&password=secret"
            - name: FTL_CONTROLLER_BIND
              value: "http://$(MY_POD_IP):8892"
            - name: FTL_CONTROLLER_ADVERTISE
              value: "http://ftl-controller:8892"
          ports:
            - containerPort: 8892
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8892
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 15
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftl-controller
  name: ftl-controller
spec:
  ports:
    - name: 80-8892
      port: 80
      protocol: TCP
      targetPort: 8892
  selector:
    app: ftl-controller
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftl-controller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ftl-controller
  minReplicas: 1
  maxReplicas: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ftl-controller
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ftl-controller
                port:
                  number: 80
