apiVersion: v1
kind: ConfigMap
metadata:
  name: ftl-controller-deployment-config
data:
  serviceTemplate: |-
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "(replaced)"
      name: "(replaced)"
    spec:
      ports:
        - name: verbs
          protocol: TCP
          port: 8893
          targetPort: 8893
      type: ClusterIP
  deploymentTemplate: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: ftl-runner
    spec:
      selector:
        matchLabels:
          app: ftl-runner
      template:
        metadata:
          labels:
            app: ftl-runner
        spec:
          containers:
            - name: app
              env:
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: LOG_LEVEL
                  value: "debug"
                - name: FTL_ENDPOINT
                  value: "http://ftl-controller:8892"
                - name: FTL_RUNNER_BIND
                  value: "http://$(MY_POD_IP):8893"
                - name: FTL_RUNNER_ADVERTISE
                  value: "http://$(MY_POD_IP):8893"
                - name: FTL_LANGUAGE
                  value: "go,kotlin,java"
                - name: LOG_TIMESTAMPS
                  value: "true"
              ports:
                - containerPort: 8893
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: 8893
                initialDelaySeconds: 1
                periodSeconds: 2
                timeoutSeconds: 2
                successThreshold: 1
                failureThreshold: 15
    serviceAccountTemplate: |- 
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        labels:
          app: ftl-runner
