apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ftl-controller
    app.kubernetes.io/managed-by: kustomize
  name: ftl-controller
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts"]
    verbs: [ "get", "list", "watch", "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames:
      - ftl-controller-deployment-config
    verbs: [ "get"]
  - apiGroups: [ "security.istio.io" ]
    resources: [ "authorizationpolicies" ]
    verbs: [ "get", "list", "watch", "create" ]
