apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftl-controller
  labels:
    app: ftl-controller
spec:
  selector:
    matchLabels:
      app: ftl-controller
  template:
    metadata:
      labels:
        app: ftl-controller
    spec:
      containers:
      - name: app
        image: ghcr.io/tbd54566975/ftl-controller:latest
        env:
        - name: FTL_CONTROLLER_DSN
          value: "postgres://ftl-pg-cluster/ftl?sslmode=disable&user=postgres&password=secret"
        ports:
          - containerPort: 8899
