apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-admin
  {{- if .Values.admin.service.annotations }}
  annotations:
    {{- toYaml .Values.admin.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    {{- range .Values.admin.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      protocol: {{ .protocol | default "TCP" }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "ftl-admin.selectorLabels" . | nindent 4 }}
  type: {{ .Values.admin.service.type | default "ClusterIP" }}
