apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.controller.controllersRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.controller.controllersRoleArn }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ftl.fullname" . }}-controller
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" , "serviceaccounts"]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames:
      - ftl-controller-deployment-config
    verbs: [ "get"]
  - apiGroups: [ "security.istio.io" ]
    resources: [ "authorizationpolicies" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ftl.fullname" . }}-controller
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ftl.fullname" . }}-controller
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccountName }}
