apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.controller.controllersRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.controller.controllersRoleArn }}
  {{- end }}
