apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.cron.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.cron.cronsRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.cron.cronsRoleArn }}
  {{- end }}
