{{- if .Values.dbMigration.enabled }}
{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ftl.fullname" . }}-dbmig-{{ .Values.controller.image.tag | default $version }}
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  activeDeadlineSeconds: 900
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "ftl.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "ftl.fullname" . }}-dbmig
      restartPolicy: OnFailure
      containers:
        - name: dbmig
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default $version }}"
          env:
            {{- if not .Values.postgresql.enabled }}
            - name: DATABASE_URL
              value: "{{ .Values.controller.dbConnectionString }}"
            {{- else }}
            - name: DATABASE_URL
              value: "postgres://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.global.postgresql.auth.database }}?sslmode=disable&user={{ .Values.postgresql.global.postgresql.auth.username }}&password={{ .Values.postgresql.global.postgresql.auth.password }}"
            {{- end }}
          command:
            - /root/ftl
            - migrate
  backoffLimit: 4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ftl.fullname" . }}-dbmig
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ftl.fullname" . }}-dbmig-role
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ftl.fullname" . }}-dbmig-rolebinding
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ftl.fullname" . }}-dbmig-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ftl.fullname" . }}-dbmig
    namespace: {{ .Release.Namespace }}
{{- end }}
