{{- if .Values.ingress.enabled }}
{{ $fullName := include "ftl.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ftl.fullname" . }}-controller
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ftl-controller
              port:
                number: 8892
  {{- range $host := .Values.ingress.hosts }}
  - host: {{ $host.host }}
    http:
      paths:
      {{- range $host.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $fullName }}-controller
            port:
              number: {{ $host.service.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls: {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
