{{- if .Values.ingress.enabled }}
{{ $fullName := include "ftl.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ftl.fullname" . }}-ingress
  annotations:
    {{- toYaml .Values.ingress.ingressAnnotations | nindent 4 }}
spec:
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ftl-controller
              port:
                number: 8892
        - path: /ingress/
          pathType: Prefix
          backend:
            service:
              name: ftl-http-ingress
              port:
                number: 8891
        - path: /xyz.block.ftl.provisioner.v1beta1.ProvisionerService/
          pathType: Prefix
          backend:
            service:
              name: ftl-provisioner
              port:
                number: 8893
  {{- range $host := .Values.ingress.hosts }}
  - host: "{{ $host.host }}"
    http:
      paths:
      {{- range $host.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $host.service.name }}
            port:
              number: {{ $host.service.port }}
      {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls: {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
