{{- if eq .Values.provisioner.configMap "ftl-provisioner-default-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftl-provisioner-default-config
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    plugins = [
        { id = "cloudformation", resources = ["postgres"] },
        { id = "controller", resources = ["module"] },
    ]
{{- end}}