{{- if .Values.provisioner.enabled }}
{{- if eq .Values.provisioner.configMap "ftl-provisioner-default-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftl-provisioner-default-config
  namespace: default
data:
  config.toml: |
    default = "controller"
    plugins = [
        { id = "cloudformation", resources = ["postgres"] },
        { id = "controller", resources = ["module"] },
    ]
{{- end}}
{{- end}}