apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.provisioner.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.provisioner.provisionersRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.provisioner.provisionersRoleArn }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ftl.fullname" . }}-provisioner
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames:
      - {{ .Values.provisioner.configMap }}
    verbs: [ "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ftl.fullname" . }}-provisioner
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ftl.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ .Values.provisioner.serviceAccountName }}
