{{- if .Values.registry.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ftl.fullname" . }}-registry
  {{- if .Values.registry.service.annotations }}
  annotations:
    {{- toYaml .Values.registry.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry
  type:  "ClusterIP"
{{- end }}