apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ftl.fullname" . }}-secrets
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
type: Opaque
stringData:
  FTL_LOG_ENCRYPTION_KEY: {{ .Values.secrets.logEncryptionKey }}
  FTL_ASYNC_ENCRYPTION_KEY: {{ .Values.secrets.asyncEncryptionKey }}
  FTL_CONTROLLER_REGISTRY_USERNAME: {{ .Values.secrets.controllerRegistryUsername }}
  FTL_CONTROLLER_REGISTRY_PASSWORD: {{ .Values.secrets.controllerRegistryPassword }}
  FTL_RUNNER_REGISTRY_USERNAME: {{ .Values.secrets.runnerRegistryUsername }}
  FTL_RUNNER_REGISTRY_PASSWORD: {{ .Values.secrets.runnerRegistryPassword }}