# yaml-language-server: $schema=./.go-arch-lint-schema.json
version: 3
workdir: .
components:
  controller: { in: backend/controller/** }
  ftl-controller-cmd: { in: cmd/ftl-controller/** }
  common-plugin: { in: common/plugin/** }
  common: { in: common/** }
  common-tests: { in: common/internal/tests/** }
  internal: { in: internal/** }
  ftl-version: { in: . }

  libdal: { in: backend/libdal/** }
  lease-service: { in: backend/lease/** }
  cron-service: { in: backend/cron/** }
  ingress-service: { in: backend/ingress/** }
  timeline-service: { in: backend/timeline/** }
  provisioner-service: { in: backend/provisioner/** }
  backend-protos: {in: backend/protos/**}

  ftl: { in: . }

  go-runtime: { in: go-runtime/** }
  jvm-runtime: { in: jvm-runtime/** }
  python-runtime: { in: python-runtime/** }

  runner: { in: backend/runner/** }

  ftl-cmd: { in: frontend/cli/** }
  frontend: { in: frontend/console/** }

  ftl-runner-cmd: { in: cmd/ftl-runner/** }
  ftl-gen-lsp-cmd: { in: cmd/ftl-gen-lsp/** }
  ftl-initdb-cmd: { in: cmd/ftl-initdb/** }
  ftl-provisioner-cloudformation-cmd: { in: cmd/ftl-provisioner-cloudformation/** }
  ftl-lease-cmd: { in: cmd/ftl-lease/** }
  ftl-http-ingress-cmd: { in: cmd/ftl-http-ingress/** }
  ftl-cron-cmd: { in: cmd/ftl-cron/** }
  ftl-timeline-cmd: { in: cmd/ftl-timeline/** }
  ftl-provisioner-cmd: { in: cmd/ftl-provisioner/** }
  ftl-proxy-pg-cmd: { in: cmd/ftl-proxy-pg/** }
  devel-provisioner-cmd: { in: cmd/devel-provisioner/** }

  go2proto: { in: cmd/go2proto/** }

  lint-commit-or-rollback-cmd: { in: cmd/lint-commit-or-rollback/** }

  smoketest: { in: smoketest/** }


excludeFiles:
  - ".*/testdata/.*"
  - ".*/\\.ftl/.*"
  - "/examples/.*"
  - "/jvm-runtime/.*"

allow:
  depOnAnyVendor: true

commonComponents:
  - common
  - ftl-version

deps:
  backend-protos:
    mayDependOn:
      - backend-protos
      - internal
  controller:
    mayDependOn:
      - controller
      - frontend
      - timeline-service #TODO: Timeline should have a separate client package.
      - internal
      - libdal
      - backend-protos
  frontend:
    mayDependOn:
      - internal
  runner:
    mayDependOn:
      - runner
      - internal
      - backend-protos
  go-runtime:
    mayDependOn:
      - go-runtime
      - internal
      - backend-protos
  python-runtime:
    mayDependOn:
      - python-runtime
      - internal
      - backend-protos
  jvm-runtime:
    mayDependOn:
      - jvm-runtime
      - internal
      - backend-protos
  ftl-cmd:
    mayDependOn:
      - controller
      - ftl
      - jvm-runtime # TODO: When we decouple runtimes, this should be removed.
      - go-runtime # TODO: When we decouple runtimes, this should be removed.
      - provisioner-service
      - timeline-service
      - ingress-service
      - cron-service
      - internal
      - backend-protos
      - lease-service
  ftl-controller-cmd:
    mayDependOn:
      - controller
      - ftl
      - timeline-service #TODO: Timeline should have a separate client package.
      - internal
      - backend-protos
  ftl-runner-cmd:
    mayDependOn:
      - runner
      - internal
      - backend-protos
  ftl-initdb-cmd:
    mayDependOn:
      - internal
  ftl-cron-cmd:
    mayDependOn:
      - cron-service
      - timeline-service #TODO: Timeline should have a separate client package.
      - internal
      - backend-protos
  ftl-http-ingress-cmd:
    mayDependOn:
      - ingress-service
      - timeline-service #TODO: Timeline should have a separate client package.
      - internal
      - backend-protos
  ftl-provisioner-cmd:
    mayDependOn:
      - provisioner-service
      - internal
      - backend-protos
  ftl-provisioner-cloudformation-cmd:
    mayDependOn:
      - provisioner-service
      - internal
      - backend-protos
  ftl-proxy-pg-cmd:
    mayDependOn:
      - internal
  ftl-timeline-cmd:
    mayDependOn:
      - timeline-service
      - internal
      - backend-protos
  ftl-lease-cmd:
    mayDependOn:
      - lease-service
      - internal
      - backend-protos
  cron-service:
    mayDependOn:
      - cron-service
      - timeline-service #TODO: Timeline should have a separate client package.
      - internal
      - backend-protos
  ingress-service:
    mayDependOn:
      - ingress-service
      - timeline-service #TODO: Timeline should have a separate client package.
      - internal
      - backend-protos
  provisioner-service:
    mayDependOn:
      - provisioner-service
      - internal
      - backend-protos
  timeline-service:
    mayDependOn:
      - internal
      - backend-protos
  lease-service:
    mayDependOn:
      - internal
      - backend-protos
  smoketest:
    mayDependOn:
      - go-runtime
  common-plugin:
    mayDependOn:
      - internal
      - backend-protos
  internal:
    mayDependOn:
      - internal
      - backend-protos
  common-tests:
    mayDependOn:
      - internal
      - go-runtime
