FROM ubuntu:24.04 AS builder
RUN apt-get update
RUN apt-get install -y curl git zip

# Seed some of the most common tools - this will be cached
COPY ./bin /src/bin
ENV PATH="/src/bin:$PATH"
ENV HERMIT_STATE_DIR=/hermit
RUN hermit install openjdk-17.0.8_7
RUN mvn -B --version

# Finally create the runtime image.
FROM ftl0/ftl-runner:latest

WORKDIR /root/

ENV PATH="/root/jdk/bin:$PATH"
ENV JAVA_HOME="/root/jdk"
COPY --from=builder /hermit/pkg/openjdk-17.0.8_7/ /root/jdk/
RUN mkdir deployments
