name = "ftl"
module-dirs = ["examples/go"]
disable-ide-integration = true

[global]
  [global.configuration]
    key = "inline://InZhbHVlIg"

[modules]
  [modules.echo]
    [modules.echo.configuration]
      default = "inline://ImFub255bW91cyI"
  [modules.test]
    [modules.test.configuration]
    [modules.test.secrets]

[commands]
  startup = ["echo 'FTL startup command ⚡️'"]
