module-dirs = ["examples/go"]
external-dirs = []

[global]

[modules]
  [modules.echo]
    [modules.echo.configuration]
      default = "inline://ImFub255bW91cyI"

[commands]
  startup = ["echo 'FTL startup command ⚡️'"]
