module-dirs = ["examples/go"]
external-dirs = []
ftl-min-version = ""

[global]
  [global.configuration]
    key = "inline://InZhbHVlIg"

[modules]
  [modules.echo]
    [modules.echo.configuration]
      default = "inline://ImFub255bW91cyI"

[commands]
  startup = ["echo 'FTL startup command ⚡️'"]
