name = "ftl"
module-dirs = ["examples/go", "exemplar"]
ftl-min-version = ""
hermit = false
no-git = false
disable-ide-integration = true

[global]
  [global.configuration]
    CUSTOMER_TOKEN_TBD = "inline://InNvbWVDb25maWci"
    key = "inline://InZhbHVlIg"

[modules]
  [modules.echo]
    [modules.echo.configuration]
      default = "inline://ImFub255bW91cyI"
  [modules.test]
    [modules.test.configuration]
    [modules.test.secrets]

[commands]
  startup = ["echo 'FTL startup command ⚡️'"]
