// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file xyz/block/ftl/timeline/v1/event.proto (package xyz.block.ftl.timeline.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";
import { Ref } from "../../schema/v1/schema_pb.js";

/**
 * @generated from enum xyz.block.ftl.timeline.v1.EventType
 */
export enum EventType {
  /**
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: EVENT_TYPE_LOG = 1;
   */
  LOG = 1,

  /**
   * @generated from enum value: EVENT_TYPE_CALL = 2;
   */
  CALL = 2,

  /**
   * @generated from enum value: EVENT_TYPE_DEPLOYMENT_CREATED = 3;
   */
  DEPLOYMENT_CREATED = 3,

  /**
   * @generated from enum value: EVENT_TYPE_DEPLOYMENT_UPDATED = 4;
   */
  DEPLOYMENT_UPDATED = 4,

  /**
   * @generated from enum value: EVENT_TYPE_INGRESS = 5;
   */
  INGRESS = 5,

  /**
   * @generated from enum value: EVENT_TYPE_CRON_SCHEDULED = 6;
   */
  CRON_SCHEDULED = 6,

  /**
   * @generated from enum value: EVENT_TYPE_ASYNC_EXECUTE = 7;
   */
  ASYNC_EXECUTE = 7,

  /**
   * @generated from enum value: EVENT_TYPE_PUBSUB_PUBLISH = 8;
   */
  PUBSUB_PUBLISH = 8,

  /**
   * @generated from enum value: EVENT_TYPE_PUBSUB_CONSUME = 9;
   */
  PUBSUB_CONSUME = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(EventType)
proto3.util.setEnumType(EventType, "xyz.block.ftl.timeline.v1.EventType", [
  { no: 0, name: "EVENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "EVENT_TYPE_LOG" },
  { no: 2, name: "EVENT_TYPE_CALL" },
  { no: 3, name: "EVENT_TYPE_DEPLOYMENT_CREATED" },
  { no: 4, name: "EVENT_TYPE_DEPLOYMENT_UPDATED" },
  { no: 5, name: "EVENT_TYPE_INGRESS" },
  { no: 6, name: "EVENT_TYPE_CRON_SCHEDULED" },
  { no: 7, name: "EVENT_TYPE_ASYNC_EXECUTE" },
  { no: 8, name: "EVENT_TYPE_PUBSUB_PUBLISH" },
  { no: 9, name: "EVENT_TYPE_PUBSUB_CONSUME" },
]);

/**
 * @generated from enum xyz.block.ftl.timeline.v1.AsyncExecuteEventType
 */
export enum AsyncExecuteEventType {
  /**
   * @generated from enum value: ASYNC_EXECUTE_EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ASYNC_EXECUTE_EVENT_TYPE_CRON = 1;
   */
  CRON = 1,

  /**
   * @generated from enum value: ASYNC_EXECUTE_EVENT_TYPE_PUBSUB = 2;
   */
  PUBSUB = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(AsyncExecuteEventType)
proto3.util.setEnumType(AsyncExecuteEventType, "xyz.block.ftl.timeline.v1.AsyncExecuteEventType", [
  { no: 0, name: "ASYNC_EXECUTE_EVENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "ASYNC_EXECUTE_EVENT_TYPE_CRON" },
  { no: 2, name: "ASYNC_EXECUTE_EVENT_TYPE_PUBSUB" },
]);

/**
 * @generated from enum xyz.block.ftl.timeline.v1.LogLevel
 */
export enum LogLevel {
  /**
   * @generated from enum value: LOG_LEVEL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOG_LEVEL_TRACE = 1;
   */
  TRACE = 1,

  /**
   * @generated from enum value: LOG_LEVEL_DEBUG = 5;
   */
  DEBUG = 5,

  /**
   * @generated from enum value: LOG_LEVEL_INFO = 9;
   */
  INFO = 9,

  /**
   * @generated from enum value: LOG_LEVEL_WARN = 13;
   */
  WARN = 13,

  /**
   * @generated from enum value: LOG_LEVEL_ERROR = 17;
   */
  ERROR = 17,
}
// Retrieve enum metadata with: proto3.getEnumType(LogLevel)
proto3.util.setEnumType(LogLevel, "xyz.block.ftl.timeline.v1.LogLevel", [
  { no: 0, name: "LOG_LEVEL_UNSPECIFIED" },
  { no: 1, name: "LOG_LEVEL_TRACE" },
  { no: 5, name: "LOG_LEVEL_DEBUG" },
  { no: 9, name: "LOG_LEVEL_INFO" },
  { no: 13, name: "LOG_LEVEL_WARN" },
  { no: 17, name: "LOG_LEVEL_ERROR" },
]);

/**
 * @generated from message xyz.block.ftl.timeline.v1.LogEvent
 */
export class LogEvent extends Message<LogEvent> {
  /**
   * @generated from field: string deployment_key = 1;
   */
  deploymentKey = "";

  /**
   * @generated from field: optional string request_key = 2;
   */
  requestKey?: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: int32 log_level = 4;
   */
  logLevel = 0;

  /**
   * @generated from field: map<string, string> attributes = 5;
   */
  attributes: { [key: string]: string } = {};

  /**
   * @generated from field: string message = 6;
   */
  message = "";

  /**
   * @generated from field: optional string error = 7;
   */
  error?: string;

  /**
   * @generated from field: optional string stack = 8;
   */
  stack?: string;

  constructor(data?: PartialMessage<LogEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.LogEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "request_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "timestamp", kind: "message", T: Timestamp },
    { no: 4, name: "log_level", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "attributes", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
    { no: 6, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 8, name: "stack", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogEvent {
    return new LogEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogEvent {
    return new LogEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogEvent {
    return new LogEvent().fromJsonString(jsonString, options);
  }

  static equals(a: LogEvent | PlainMessage<LogEvent> | undefined, b: LogEvent | PlainMessage<LogEvent> | undefined): boolean {
    return proto3.util.equals(LogEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.CallEvent
 */
export class CallEvent extends Message<CallEvent> {
  /**
   * @generated from field: optional string request_key = 1;
   */
  requestKey?: string;

  /**
   * @generated from field: string deployment_key = 2;
   */
  deploymentKey = "";

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: optional xyz.block.ftl.schema.v1.Ref source_verb_ref = 11;
   */
  sourceVerbRef?: Ref;

  /**
   * @generated from field: xyz.block.ftl.schema.v1.Ref destination_verb_ref = 12;
   */
  destinationVerbRef?: Ref;

  /**
   * @generated from field: google.protobuf.Duration duration = 6;
   */
  duration?: Duration;

  /**
   * @generated from field: string request = 7;
   */
  request = "";

  /**
   * @generated from field: string response = 8;
   */
  response = "";

  /**
   * @generated from field: optional string error = 9;
   */
  error?: string;

  /**
   * @generated from field: optional string stack = 10;
   */
  stack?: string;

  constructor(data?: PartialMessage<CallEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.CallEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "request_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "timestamp", kind: "message", T: Timestamp },
    { no: 11, name: "source_verb_ref", kind: "message", T: Ref, opt: true },
    { no: 12, name: "destination_verb_ref", kind: "message", T: Ref },
    { no: 6, name: "duration", kind: "message", T: Duration },
    { no: 7, name: "request", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "response", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 10, name: "stack", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CallEvent {
    return new CallEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CallEvent {
    return new CallEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CallEvent {
    return new CallEvent().fromJsonString(jsonString, options);
  }

  static equals(a: CallEvent | PlainMessage<CallEvent> | undefined, b: CallEvent | PlainMessage<CallEvent> | undefined): boolean {
    return proto3.util.equals(CallEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.DeploymentCreatedEvent
 */
export class DeploymentCreatedEvent extends Message<DeploymentCreatedEvent> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: string language = 2;
   */
  language = "";

  /**
   * @generated from field: string module_name = 3;
   */
  moduleName = "";

  /**
   * @generated from field: int32 min_replicas = 4;
   */
  minReplicas = 0;

  /**
   * @generated from field: optional string replaced = 5;
   */
  replaced?: string;

  constructor(data?: PartialMessage<DeploymentCreatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.DeploymentCreatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "language", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "module_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "min_replicas", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 5, name: "replaced", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentCreatedEvent {
    return new DeploymentCreatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentCreatedEvent {
    return new DeploymentCreatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentCreatedEvent {
    return new DeploymentCreatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentCreatedEvent | PlainMessage<DeploymentCreatedEvent> | undefined, b: DeploymentCreatedEvent | PlainMessage<DeploymentCreatedEvent> | undefined): boolean {
    return proto3.util.equals(DeploymentCreatedEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent
 */
export class DeploymentUpdatedEvent extends Message<DeploymentUpdatedEvent> {
  /**
   * @generated from field: string key = 1;
   */
  key = "";

  /**
   * @generated from field: int32 min_replicas = 2;
   */
  minReplicas = 0;

  /**
   * @generated from field: int32 prev_min_replicas = 3;
   */
  prevMinReplicas = 0;

  constructor(data?: PartialMessage<DeploymentUpdatedEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "min_replicas", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "prev_min_replicas", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeploymentUpdatedEvent {
    return new DeploymentUpdatedEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeploymentUpdatedEvent {
    return new DeploymentUpdatedEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeploymentUpdatedEvent {
    return new DeploymentUpdatedEvent().fromJsonString(jsonString, options);
  }

  static equals(a: DeploymentUpdatedEvent | PlainMessage<DeploymentUpdatedEvent> | undefined, b: DeploymentUpdatedEvent | PlainMessage<DeploymentUpdatedEvent> | undefined): boolean {
    return proto3.util.equals(DeploymentUpdatedEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.IngressEvent
 */
export class IngressEvent extends Message<IngressEvent> {
  /**
   * @generated from field: string deployment_key = 1;
   */
  deploymentKey = "";

  /**
   * @generated from field: optional string request_key = 2;
   */
  requestKey?: string;

  /**
   * @generated from field: xyz.block.ftl.schema.v1.Ref verb_ref = 3;
   */
  verbRef?: Ref;

  /**
   * @generated from field: string method = 4;
   */
  method = "";

  /**
   * @generated from field: string path = 5;
   */
  path = "";

  /**
   * @generated from field: int32 status_code = 7;
   */
  statusCode = 0;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 8;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 9;
   */
  duration?: Duration;

  /**
   * @generated from field: string request = 10;
   */
  request = "";

  /**
   * @generated from field: string request_header = 11;
   */
  requestHeader = "";

  /**
   * @generated from field: string response = 12;
   */
  response = "";

  /**
   * @generated from field: string response_header = 13;
   */
  responseHeader = "";

  /**
   * @generated from field: optional string error = 14;
   */
  error?: string;

  constructor(data?: PartialMessage<IngressEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.IngressEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "request_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "verb_ref", kind: "message", T: Ref },
    { no: 4, name: "method", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "status_code", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 8, name: "timestamp", kind: "message", T: Timestamp },
    { no: 9, name: "duration", kind: "message", T: Duration },
    { no: 10, name: "request", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "request_header", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "response", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "response_header", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 14, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): IngressEvent {
    return new IngressEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): IngressEvent {
    return new IngressEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): IngressEvent {
    return new IngressEvent().fromJsonString(jsonString, options);
  }

  static equals(a: IngressEvent | PlainMessage<IngressEvent> | undefined, b: IngressEvent | PlainMessage<IngressEvent> | undefined): boolean {
    return proto3.util.equals(IngressEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.CronScheduledEvent
 */
export class CronScheduledEvent extends Message<CronScheduledEvent> {
  /**
   * @generated from field: string deployment_key = 1;
   */
  deploymentKey = "";

  /**
   * @generated from field: xyz.block.ftl.schema.v1.Ref verb_ref = 2;
   */
  verbRef?: Ref;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 4;
   */
  duration?: Duration;

  /**
   * @generated from field: google.protobuf.Timestamp scheduled_at = 5;
   */
  scheduledAt?: Timestamp;

  /**
   * @generated from field: string schedule = 6;
   */
  schedule = "";

  /**
   * @generated from field: optional string error = 7;
   */
  error?: string;

  constructor(data?: PartialMessage<CronScheduledEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.CronScheduledEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "verb_ref", kind: "message", T: Ref },
    { no: 3, name: "timestamp", kind: "message", T: Timestamp },
    { no: 4, name: "duration", kind: "message", T: Duration },
    { no: 5, name: "scheduled_at", kind: "message", T: Timestamp },
    { no: 6, name: "schedule", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CronScheduledEvent {
    return new CronScheduledEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CronScheduledEvent {
    return new CronScheduledEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CronScheduledEvent {
    return new CronScheduledEvent().fromJsonString(jsonString, options);
  }

  static equals(a: CronScheduledEvent | PlainMessage<CronScheduledEvent> | undefined, b: CronScheduledEvent | PlainMessage<CronScheduledEvent> | undefined): boolean {
    return proto3.util.equals(CronScheduledEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.AsyncExecuteEvent
 */
export class AsyncExecuteEvent extends Message<AsyncExecuteEvent> {
  /**
   * @generated from field: string deployment_key = 1;
   */
  deploymentKey = "";

  /**
   * @generated from field: optional string request_key = 2;
   */
  requestKey?: string;

  /**
   * @generated from field: xyz.block.ftl.schema.v1.Ref verb_ref = 3;
   */
  verbRef?: Ref;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 5;
   */
  duration?: Duration;

  /**
   * @generated from field: xyz.block.ftl.timeline.v1.AsyncExecuteEventType async_event_type = 6;
   */
  asyncEventType = AsyncExecuteEventType.UNSPECIFIED;

  /**
   * @generated from field: optional string error = 7;
   */
  error?: string;

  constructor(data?: PartialMessage<AsyncExecuteEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.AsyncExecuteEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "request_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "verb_ref", kind: "message", T: Ref },
    { no: 4, name: "timestamp", kind: "message", T: Timestamp },
    { no: 5, name: "duration", kind: "message", T: Duration },
    { no: 6, name: "async_event_type", kind: "enum", T: proto3.getEnumType(AsyncExecuteEventType) },
    { no: 7, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AsyncExecuteEvent {
    return new AsyncExecuteEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AsyncExecuteEvent {
    return new AsyncExecuteEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AsyncExecuteEvent {
    return new AsyncExecuteEvent().fromJsonString(jsonString, options);
  }

  static equals(a: AsyncExecuteEvent | PlainMessage<AsyncExecuteEvent> | undefined, b: AsyncExecuteEvent | PlainMessage<AsyncExecuteEvent> | undefined): boolean {
    return proto3.util.equals(AsyncExecuteEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.PubSubPublishEvent
 */
export class PubSubPublishEvent extends Message<PubSubPublishEvent> {
  /**
   * @generated from field: string deployment_key = 1;
   */
  deploymentKey = "";

  /**
   * @generated from field: optional string request_key = 2;
   */
  requestKey?: string;

  /**
   * @generated from field: xyz.block.ftl.schema.v1.Ref verb_ref = 3;
   */
  verbRef?: Ref;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 5;
   */
  duration?: Duration;

  /**
   * @generated from field: string topic = 6;
   */
  topic = "";

  /**
   * @generated from field: string request = 7;
   */
  request = "";

  /**
   * @generated from field: optional string error = 8;
   */
  error?: string;

  /**
   * @generated from field: int32 partition = 9;
   */
  partition = 0;

  /**
   * @generated from field: int64 offset = 10;
   */
  offset = protoInt64.zero;

  constructor(data?: PartialMessage<PubSubPublishEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.PubSubPublishEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "request_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "verb_ref", kind: "message", T: Ref },
    { no: 4, name: "timestamp", kind: "message", T: Timestamp },
    { no: 5, name: "duration", kind: "message", T: Duration },
    { no: 6, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "request", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "partition", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "offset", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PubSubPublishEvent {
    return new PubSubPublishEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PubSubPublishEvent {
    return new PubSubPublishEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PubSubPublishEvent {
    return new PubSubPublishEvent().fromJsonString(jsonString, options);
  }

  static equals(a: PubSubPublishEvent | PlainMessage<PubSubPublishEvent> | undefined, b: PubSubPublishEvent | PlainMessage<PubSubPublishEvent> | undefined): boolean {
    return proto3.util.equals(PubSubPublishEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.PubSubConsumeEvent
 */
export class PubSubConsumeEvent extends Message<PubSubConsumeEvent> {
  /**
   * @generated from field: string deployment_key = 1;
   */
  deploymentKey = "";

  /**
   * @generated from field: optional string request_key = 2;
   */
  requestKey?: string;

  /**
   * @generated from field: optional string dest_verb_module = 3;
   */
  destVerbModule?: string;

  /**
   * @generated from field: optional string dest_verb_name = 4;
   */
  destVerbName?: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 5;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 6;
   */
  duration?: Duration;

  /**
   * @generated from field: string topic = 7;
   */
  topic = "";

  /**
   * @generated from field: optional string error = 8;
   */
  error?: string;

  /**
   * @generated from field: int32 partition = 9;
   */
  partition = 0;

  /**
   * @generated from field: int64 offset = 10;
   */
  offset = protoInt64.zero;

  constructor(data?: PartialMessage<PubSubConsumeEvent>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.PubSubConsumeEvent";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "deployment_key", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "request_key", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 3, name: "dest_verb_module", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 4, name: "dest_verb_name", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 5, name: "timestamp", kind: "message", T: Timestamp },
    { no: 6, name: "duration", kind: "message", T: Duration },
    { no: 7, name: "topic", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 9, name: "partition", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 10, name: "offset", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PubSubConsumeEvent {
    return new PubSubConsumeEvent().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PubSubConsumeEvent {
    return new PubSubConsumeEvent().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PubSubConsumeEvent {
    return new PubSubConsumeEvent().fromJsonString(jsonString, options);
  }

  static equals(a: PubSubConsumeEvent | PlainMessage<PubSubConsumeEvent> | undefined, b: PubSubConsumeEvent | PlainMessage<PubSubConsumeEvent> | undefined): boolean {
    return proto3.util.equals(PubSubConsumeEvent, a, b);
  }
}

/**
 * @generated from message xyz.block.ftl.timeline.v1.Event
 */
export class Event extends Message<Event> {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * Unique ID for event.
   *
   * @generated from field: int64 id = 2;
   */
  id = protoInt64.zero;

  /**
   * @generated from oneof xyz.block.ftl.timeline.v1.Event.entry
   */
  entry: {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.LogEvent log = 3;
     */
    value: LogEvent;
    case: "log";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.CallEvent call = 4;
     */
    value: CallEvent;
    case: "call";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.DeploymentCreatedEvent deployment_created = 5;
     */
    value: DeploymentCreatedEvent;
    case: "deploymentCreated";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent deployment_updated = 6;
     */
    value: DeploymentUpdatedEvent;
    case: "deploymentUpdated";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.IngressEvent ingress = 7;
     */
    value: IngressEvent;
    case: "ingress";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.CronScheduledEvent cron_scheduled = 8;
     */
    value: CronScheduledEvent;
    case: "cronScheduled";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.AsyncExecuteEvent async_execute = 9;
     */
    value: AsyncExecuteEvent;
    case: "asyncExecute";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.PubSubPublishEvent pubsub_publish = 10;
     */
    value: PubSubPublishEvent;
    case: "pubsubPublish";
  } | {
    /**
     * @generated from field: xyz.block.ftl.timeline.v1.PubSubConsumeEvent pubsub_consume = 11;
     */
    value: PubSubConsumeEvent;
    case: "pubsubConsume";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<Event>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "xyz.block.ftl.timeline.v1.Event";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "timestamp", kind: "message", T: Timestamp },
    { no: 2, name: "id", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "log", kind: "message", T: LogEvent, oneof: "entry" },
    { no: 4, name: "call", kind: "message", T: CallEvent, oneof: "entry" },
    { no: 5, name: "deployment_created", kind: "message", T: DeploymentCreatedEvent, oneof: "entry" },
    { no: 6, name: "deployment_updated", kind: "message", T: DeploymentUpdatedEvent, oneof: "entry" },
    { no: 7, name: "ingress", kind: "message", T: IngressEvent, oneof: "entry" },
    { no: 8, name: "cron_scheduled", kind: "message", T: CronScheduledEvent, oneof: "entry" },
    { no: 9, name: "async_execute", kind: "message", T: AsyncExecuteEvent, oneof: "entry" },
    { no: 10, name: "pubsub_publish", kind: "message", T: PubSubPublishEvent, oneof: "entry" },
    { no: 11, name: "pubsub_consume", kind: "message", T: PubSubConsumeEvent, oneof: "entry" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Event {
    return new Event().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Event {
    return new Event().fromJsonString(jsonString, options);
  }

  static equals(a: Event | PlainMessage<Event> | undefined, b: Event | PlainMessage<Event> | undefined): boolean {
    return proto3.util.equals(Event, a, b);
  }
}

