// Code generated by Wire protocol buffer compiler, do not edit.
// Source: xyz.block.ftl.v1.DeploymentChangeType in xyz/block/ftl/v1/ftl.proto
package xyz.block.ftl.v1

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import kotlin.Int
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic

public enum class DeploymentChangeType(
  public override val `value`: Int,
) : WireEnum {
  DEPLOYMENT_ADDED(0),
  DEPLOYMENT_REMOVED(1),
  DEPLOYMENT_CHANGED(2),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<DeploymentChangeType> = object :
        EnumAdapter<DeploymentChangeType>(
      DeploymentChangeType::class, 
      PROTO_3, 
      DeploymentChangeType.DEPLOYMENT_ADDED
    ) {
      public override fun fromValue(`value`: Int): DeploymentChangeType? =
          DeploymentChangeType.fromValue(value)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): DeploymentChangeType? = when (value) {
      0 -> DEPLOYMENT_ADDED
      1 -> DEPLOYMENT_REMOVED
      2 -> DEPLOYMENT_CHANGED
      else -> null
    }
  }
}
