// Code generated by Wire protocol buffer compiler, do not edit.
// Source: xyz.block.ftl.v1.ReplaceDeployRequest in xyz/block/ftl/v1/ftl.proto
package xyz.block.ftl.v1

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class ReplaceDeployRequest(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "deploymentKey",
  )
  public val deployment_key: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "minReplicas",
  )
  public val min_replicas: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ReplaceDeployRequest, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ReplaceDeployRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (deployment_key != other.deployment_key) return false
    if (min_replicas != other.min_replicas) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + deployment_key.hashCode()
      result = result * 37 + min_replicas.hashCode()
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    result += """deployment_key=${sanitize(deployment_key)}"""
    result += """min_replicas=$min_replicas"""
    return result.joinToString(prefix = "ReplaceDeployRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    deployment_key: String = this.deployment_key,
    min_replicas: Int = this.min_replicas,
    unknownFields: ByteString = this.unknownFields,
  ): ReplaceDeployRequest = ReplaceDeployRequest(deployment_key, min_replicas, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ReplaceDeployRequest> = object :
        ProtoAdapter<ReplaceDeployRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      ReplaceDeployRequest::class, 
      "type.googleapis.com/xyz.block.ftl.v1.ReplaceDeployRequest", 
      PROTO_3, 
      null, 
      "xyz/block/ftl/v1/ftl.proto"
    ) {
      public override fun encodedSize(`value`: ReplaceDeployRequest): Int {
        var size = value.unknownFields.size
        if (value.deployment_key != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1,
            value.deployment_key)
        if (value.min_replicas != 0) size += ProtoAdapter.INT32.encodedSizeWithTag(2,
            value.min_replicas)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: ReplaceDeployRequest): Unit {
        if (value.deployment_key != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.deployment_key)
        if (value.min_replicas != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.min_replicas)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: ReplaceDeployRequest): Unit {
        writer.writeBytes(value.unknownFields)
        if (value.min_replicas != 0) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.min_replicas)
        if (value.deployment_key != "") ProtoAdapter.STRING.encodeWithTag(writer, 1,
            value.deployment_key)
      }

      public override fun decode(reader: ProtoReader): ReplaceDeployRequest {
        var deployment_key: String = ""
        var min_replicas: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> deployment_key = ProtoAdapter.STRING.decode(reader)
            2 -> min_replicas = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ReplaceDeployRequest(
          deployment_key = deployment_key,
          min_replicas = min_replicas,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: ReplaceDeployRequest): ReplaceDeployRequest = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
