// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/v1/admin.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.v1;

public interface ConfigListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.block.ftl.v1.ConfigListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xyz.block.ftl.v1.ConfigListResponse.Config configs = 1 [json_name = "configs"];</code>
   */
  java.util.List<xyz.block.ftl.v1.ConfigListResponse.Config> 
      getConfigsList();
  /**
   * <code>repeated .xyz.block.ftl.v1.ConfigListResponse.Config configs = 1 [json_name = "configs"];</code>
   */
  xyz.block.ftl.v1.ConfigListResponse.Config getConfigs(int index);
  /**
   * <code>repeated .xyz.block.ftl.v1.ConfigListResponse.Config configs = 1 [json_name = "configs"];</code>
   */
  int getConfigsCount();
  /**
   * <code>repeated .xyz.block.ftl.v1.ConfigListResponse.Config configs = 1 [json_name = "configs"];</code>
   */
  java.util.List<? extends xyz.block.ftl.v1.ConfigListResponse.ConfigOrBuilder> 
      getConfigsOrBuilderList();
  /**
   * <code>repeated .xyz.block.ftl.v1.ConfigListResponse.Config configs = 1 [json_name = "configs"];</code>
   */
  xyz.block.ftl.v1.ConfigListResponse.ConfigOrBuilder getConfigsOrBuilder(
      int index);
}
