// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/v1/admin.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.v1;

public interface ConfigGetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.block.ftl.v1.ConfigGetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes value = 1 [json_name = "value"];</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
