// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/v1/admin.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.v1;

/**
 * Protobuf type {@code xyz.block.ftl.v1.ConfigUnsetRequest}
 */
public final class ConfigUnsetRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:xyz.block.ftl.v1.ConfigUnsetRequest)
    ConfigUnsetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      ConfigUnsetRequest.class.getName());
  }
  // Use ConfigUnsetRequest.newBuilder() to construct.
  private ConfigUnsetRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ConfigUnsetRequest() {
    provider_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return xyz.block.ftl.v1.Admin.internal_static_xyz_block_ftl_v1_ConfigUnsetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return xyz.block.ftl.v1.Admin.internal_static_xyz_block_ftl_v1_ConfigUnsetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            xyz.block.ftl.v1.ConfigUnsetRequest.class, xyz.block.ftl.v1.ConfigUnsetRequest.Builder.class);
  }

  private int bitField0_;
  public static final int PROVIDER_FIELD_NUMBER = 1;
  private int provider_ = 0;
  /**
   * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
   * @return Whether the provider field is set.
   */
  @java.lang.Override public boolean hasProvider() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
   * @return The enum numeric value on the wire for provider.
   */
  @java.lang.Override public int getProviderValue() {
    return provider_;
  }
  /**
   * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
   * @return The provider.
   */
  @java.lang.Override public xyz.block.ftl.v1.ConfigProvider getProvider() {
    xyz.block.ftl.v1.ConfigProvider result = xyz.block.ftl.v1.ConfigProvider.forNumber(provider_);
    return result == null ? xyz.block.ftl.v1.ConfigProvider.UNRECOGNIZED : result;
  }

  public static final int REF_FIELD_NUMBER = 2;
  private xyz.block.ftl.v1.ConfigRef ref_;
  /**
   * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
   * @return Whether the ref field is set.
   */
  @java.lang.Override
  public boolean hasRef() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
   * @return The ref.
   */
  @java.lang.Override
  public xyz.block.ftl.v1.ConfigRef getRef() {
    return ref_ == null ? xyz.block.ftl.v1.ConfigRef.getDefaultInstance() : ref_;
  }
  /**
   * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
   */
  @java.lang.Override
  public xyz.block.ftl.v1.ConfigRefOrBuilder getRefOrBuilder() {
    return ref_ == null ? xyz.block.ftl.v1.ConfigRef.getDefaultInstance() : ref_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, provider_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getRef());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, provider_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRef());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof xyz.block.ftl.v1.ConfigUnsetRequest)) {
      return super.equals(obj);
    }
    xyz.block.ftl.v1.ConfigUnsetRequest other = (xyz.block.ftl.v1.ConfigUnsetRequest) obj;

    if (hasProvider() != other.hasProvider()) return false;
    if (hasProvider()) {
      if (provider_ != other.provider_) return false;
    }
    if (hasRef() != other.hasRef()) return false;
    if (hasRef()) {
      if (!getRef()
          .equals(other.getRef())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProvider()) {
      hash = (37 * hash) + PROVIDER_FIELD_NUMBER;
      hash = (53 * hash) + provider_;
    }
    if (hasRef()) {
      hash = (37 * hash) + REF_FIELD_NUMBER;
      hash = (53 * hash) + getRef().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static xyz.block.ftl.v1.ConfigUnsetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static xyz.block.ftl.v1.ConfigUnsetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static xyz.block.ftl.v1.ConfigUnsetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(xyz.block.ftl.v1.ConfigUnsetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xyz.block.ftl.v1.ConfigUnsetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xyz.block.ftl.v1.ConfigUnsetRequest)
      xyz.block.ftl.v1.ConfigUnsetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.block.ftl.v1.Admin.internal_static_xyz_block_ftl_v1_ConfigUnsetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.block.ftl.v1.Admin.internal_static_xyz_block_ftl_v1_ConfigUnsetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.block.ftl.v1.ConfigUnsetRequest.class, xyz.block.ftl.v1.ConfigUnsetRequest.Builder.class);
    }

    // Construct using xyz.block.ftl.v1.ConfigUnsetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getRefFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      provider_ = 0;
      ref_ = null;
      if (refBuilder_ != null) {
        refBuilder_.dispose();
        refBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return xyz.block.ftl.v1.Admin.internal_static_xyz_block_ftl_v1_ConfigUnsetRequest_descriptor;
    }

    @java.lang.Override
    public xyz.block.ftl.v1.ConfigUnsetRequest getDefaultInstanceForType() {
      return xyz.block.ftl.v1.ConfigUnsetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public xyz.block.ftl.v1.ConfigUnsetRequest build() {
      xyz.block.ftl.v1.ConfigUnsetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public xyz.block.ftl.v1.ConfigUnsetRequest buildPartial() {
      xyz.block.ftl.v1.ConfigUnsetRequest result = new xyz.block.ftl.v1.ConfigUnsetRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(xyz.block.ftl.v1.ConfigUnsetRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.provider_ = provider_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.ref_ = refBuilder_ == null
            ? ref_
            : refBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof xyz.block.ftl.v1.ConfigUnsetRequest) {
        return mergeFrom((xyz.block.ftl.v1.ConfigUnsetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(xyz.block.ftl.v1.ConfigUnsetRequest other) {
      if (other == xyz.block.ftl.v1.ConfigUnsetRequest.getDefaultInstance()) return this;
      if (other.hasProvider()) {
        setProvider(other.getProvider());
      }
      if (other.hasRef()) {
        mergeRef(other.getRef());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              provider_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getRefFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int provider_ = 0;
    /**
     * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
     * @return Whether the provider field is set.
     */
    @java.lang.Override public boolean hasProvider() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
     * @return The enum numeric value on the wire for provider.
     */
    @java.lang.Override public int getProviderValue() {
      return provider_;
    }
    /**
     * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
     * @param value The enum numeric value on the wire for provider to set.
     * @return This builder for chaining.
     */
    public Builder setProviderValue(int value) {
      provider_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
     * @return The provider.
     */
    @java.lang.Override
    public xyz.block.ftl.v1.ConfigProvider getProvider() {
      xyz.block.ftl.v1.ConfigProvider result = xyz.block.ftl.v1.ConfigProvider.forNumber(provider_);
      return result == null ? xyz.block.ftl.v1.ConfigProvider.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
     * @param value The provider to set.
     * @return This builder for chaining.
     */
    public Builder setProvider(xyz.block.ftl.v1.ConfigProvider value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      provider_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.v1.ConfigProvider provider = 1 [json_name = "provider"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProvider() {
      bitField0_ = (bitField0_ & ~0x00000001);
      provider_ = 0;
      onChanged();
      return this;
    }

    private xyz.block.ftl.v1.ConfigRef ref_;
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.v1.ConfigRef, xyz.block.ftl.v1.ConfigRef.Builder, xyz.block.ftl.v1.ConfigRefOrBuilder> refBuilder_;
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     * @return Whether the ref field is set.
     */
    public boolean hasRef() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     * @return The ref.
     */
    public xyz.block.ftl.v1.ConfigRef getRef() {
      if (refBuilder_ == null) {
        return ref_ == null ? xyz.block.ftl.v1.ConfigRef.getDefaultInstance() : ref_;
      } else {
        return refBuilder_.getMessage();
      }
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    public Builder setRef(xyz.block.ftl.v1.ConfigRef value) {
      if (refBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ref_ = value;
      } else {
        refBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    public Builder setRef(
        xyz.block.ftl.v1.ConfigRef.Builder builderForValue) {
      if (refBuilder_ == null) {
        ref_ = builderForValue.build();
      } else {
        refBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    public Builder mergeRef(xyz.block.ftl.v1.ConfigRef value) {
      if (refBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          ref_ != null &&
          ref_ != xyz.block.ftl.v1.ConfigRef.getDefaultInstance()) {
          getRefBuilder().mergeFrom(value);
        } else {
          ref_ = value;
        }
      } else {
        refBuilder_.mergeFrom(value);
      }
      if (ref_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    public Builder clearRef() {
      bitField0_ = (bitField0_ & ~0x00000002);
      ref_ = null;
      if (refBuilder_ != null) {
        refBuilder_.dispose();
        refBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    public xyz.block.ftl.v1.ConfigRef.Builder getRefBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getRefFieldBuilder().getBuilder();
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    public xyz.block.ftl.v1.ConfigRefOrBuilder getRefOrBuilder() {
      if (refBuilder_ != null) {
        return refBuilder_.getMessageOrBuilder();
      } else {
        return ref_ == null ?
            xyz.block.ftl.v1.ConfigRef.getDefaultInstance() : ref_;
      }
    }
    /**
     * <code>.xyz.block.ftl.v1.ConfigRef ref = 2 [json_name = "ref"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.v1.ConfigRef, xyz.block.ftl.v1.ConfigRef.Builder, xyz.block.ftl.v1.ConfigRefOrBuilder> 
        getRefFieldBuilder() {
      if (refBuilder_ == null) {
        refBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            xyz.block.ftl.v1.ConfigRef, xyz.block.ftl.v1.ConfigRef.Builder, xyz.block.ftl.v1.ConfigRefOrBuilder>(
                getRef(),
                getParentForChildren(),
                isClean());
        ref_ = null;
      }
      return refBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:xyz.block.ftl.v1.ConfigUnsetRequest)
  }

  // @@protoc_insertion_point(class_scope:xyz.block.ftl.v1.ConfigUnsetRequest)
  private static final xyz.block.ftl.v1.ConfigUnsetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new xyz.block.ftl.v1.ConfigUnsetRequest();
  }

  public static xyz.block.ftl.v1.ConfigUnsetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConfigUnsetRequest>
      PARSER = new com.google.protobuf.AbstractParser<ConfigUnsetRequest>() {
    @java.lang.Override
    public ConfigUnsetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ConfigUnsetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConfigUnsetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public xyz.block.ftl.v1.ConfigUnsetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

