// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/v1/admin.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.v1;

/**
 * Protobuf enum {@code xyz.block.ftl.v1.SecretProvider}
 */
public enum SecretProvider
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>SECRET_PROVIDER_UNSPECIFIED = 0;</code>
   */
  SECRET_PROVIDER_UNSPECIFIED(0),
  /**
   * <pre>
   * Write values inline in the configuration file.
   * </pre>
   *
   * <code>SECRET_PROVIDER_INLINE = 1;</code>
   */
  SECRET_PROVIDER_INLINE(1),
  /**
   * <pre>
   * Print configuration as environment variables.
   * </pre>
   *
   * <code>SECRET_PROVIDER_ENVAR = 2;</code>
   */
  SECRET_PROVIDER_ENVAR(2),
  /**
   * <pre>
   * Write to the system keychain.
   * </pre>
   *
   * <code>SECRET_PROVIDER_KEYCHAIN = 3;</code>
   */
  SECRET_PROVIDER_KEYCHAIN(3),
  /**
   * <pre>
   * Store a secret in the 1Password vault.
   * </pre>
   *
   * <code>SECRET_PROVIDER_OP = 4;</code>
   */
  SECRET_PROVIDER_OP(4),
  /**
   * <pre>
   * Store a secret in the AWS Secrets Manager.
   * </pre>
   *
   * <code>SECRET_PROVIDER_ASM = 5;</code>
   */
  SECRET_PROVIDER_ASM(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      SecretProvider.class.getName());
  }
  /**
   * <code>SECRET_PROVIDER_UNSPECIFIED = 0;</code>
   */
  public static final int SECRET_PROVIDER_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Write values inline in the configuration file.
   * </pre>
   *
   * <code>SECRET_PROVIDER_INLINE = 1;</code>
   */
  public static final int SECRET_PROVIDER_INLINE_VALUE = 1;
  /**
   * <pre>
   * Print configuration as environment variables.
   * </pre>
   *
   * <code>SECRET_PROVIDER_ENVAR = 2;</code>
   */
  public static final int SECRET_PROVIDER_ENVAR_VALUE = 2;
  /**
   * <pre>
   * Write to the system keychain.
   * </pre>
   *
   * <code>SECRET_PROVIDER_KEYCHAIN = 3;</code>
   */
  public static final int SECRET_PROVIDER_KEYCHAIN_VALUE = 3;
  /**
   * <pre>
   * Store a secret in the 1Password vault.
   * </pre>
   *
   * <code>SECRET_PROVIDER_OP = 4;</code>
   */
  public static final int SECRET_PROVIDER_OP_VALUE = 4;
  /**
   * <pre>
   * Store a secret in the AWS Secrets Manager.
   * </pre>
   *
   * <code>SECRET_PROVIDER_ASM = 5;</code>
   */
  public static final int SECRET_PROVIDER_ASM_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SecretProvider valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SecretProvider forNumber(int value) {
    switch (value) {
      case 0: return SECRET_PROVIDER_UNSPECIFIED;
      case 1: return SECRET_PROVIDER_INLINE;
      case 2: return SECRET_PROVIDER_ENVAR;
      case 3: return SECRET_PROVIDER_KEYCHAIN;
      case 4: return SECRET_PROVIDER_OP;
      case 5: return SECRET_PROVIDER_ASM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SecretProvider>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SecretProvider> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SecretProvider>() {
          public SecretProvider findValueByNumber(int number) {
            return SecretProvider.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return xyz.block.ftl.v1.Admin.getDescriptor().getEnumTypes().get(1);
  }

  private static final SecretProvider[] VALUES = values();

  public static SecretProvider valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SecretProvider(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:xyz.block.ftl.v1.SecretProvider)
}

