// Code generated by FTL. DO NOT EDIT.
package another

import (
	"context"
	"github.com/block/ftl/common/reflection"
	lib "github.com/block/ftl/go-runtime/schema/testdata"
)

type EchoClient func(context.Context, EchoRequest) (EchoResponse, error)

func init() {
	reflection.Register(
		reflection.SumType[SecondTypeEnum](
			*new(One),
			*new(Two),
		),
		reflection.SumType[TypeEnum](
			*new(A),
			*new(B),
		),
		reflection.ExternalType(*new(lib.AnotherNonFTLType)),
		reflection.ProvideResourcesForVerb(
			Echo,
		),
	)
}
