// Code generated by FTL. DO NOT EDIT.
package ad

import (
	"context"
	ftlbuiltin "ftl/builtin"
	"github.com/TBD54566975/ftl/go-runtime/ftl"
	"github.com/TBD54566975/ftl/go-runtime/ftl/reflection"
)

type GetClient func(context.Context, ftlbuiltin.HttpRequest[ftl.Unit, ftl.Unit, AdRequest]) (ftlbuiltin.HttpResponse[AdResponse, ftl.Unit], error)

func init() {
	reflection.Register(
		reflection.ProvideResourcesForVerb(
			Get,
		),
	)
}
