export const __esModule: true
export const edge: string
export const edgePath: string
export const hoverPath: string
export const selected: string
export const moduleTitle: string
export const moduleVerb: string
export const node: string
export const callLink: string
