// Code generated by FTL. DO NOT EDIT.
package time

import (
	"github.com/TBD54566975/ftl/go-runtime/ftl"
	"github.com/TBD54566975/ftl/go-runtime/ftl/reflection"
)

type TimeClient = ftl.Verb[TimeRequest, TimeResponse]

func init() {
	reflection.Register(
		reflection.ProvideResourcesForVerb(
			Time,
		),
	)
}
