// Code generated by Wire protocol buffer compiler, do not edit.
// Source: xyz.block.ftl.v1.schema.Metadata in xyz/block/ftl/v1/schema/schema.proto
package xyz.block.ftl.v1.schema

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Unit
import kotlin.jvm.JvmField
import okio.ByteString

public class Metadata(
  @field:WireField(
    tag = 1,
    adapter = "xyz.block.ftl.v1.schema.MetadataCalls#ADAPTER",
    oneofName = "value",
  )
  public val calls: MetadataCalls? = null,
  @field:WireField(
    tag = 2,
    adapter = "xyz.block.ftl.v1.schema.MetadataIngress#ADAPTER",
    oneofName = "value",
  )
  public val ingress: MetadataIngress? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Metadata, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(calls, ingress) <= 1) {
      "At most one of calls, ingress may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  public override fun newBuilder(): Nothing = throw
      AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  public override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Metadata) return false
    if (unknownFields != other.unknownFields) return false
    if (calls != other.calls) return false
    if (ingress != other.ingress) return false
    return true
  }

  public override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (calls?.hashCode() ?: 0)
      result = result * 37 + (ingress?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  public override fun toString(): String {
    val result = mutableListOf<String>()
    if (calls != null) result += """calls=$calls"""
    if (ingress != null) result += """ingress=$ingress"""
    return result.joinToString(prefix = "Metadata{", separator = ", ", postfix = "}")
  }

  public fun copy(
    calls: MetadataCalls? = this.calls,
    ingress: MetadataIngress? = this.ingress,
    unknownFields: ByteString = this.unknownFields,
  ): Metadata = Metadata(calls, ingress, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Metadata> = object : ProtoAdapter<Metadata>(
      FieldEncoding.LENGTH_DELIMITED, 
      Metadata::class, 
      "type.googleapis.com/xyz.block.ftl.v1.schema.Metadata", 
      PROTO_3, 
      null, 
      "xyz/block/ftl/v1/schema/schema.proto"
    ) {
      public override fun encodedSize(`value`: Metadata): Int {
        var size = value.unknownFields.size
        size += MetadataCalls.ADAPTER.encodedSizeWithTag(1, value.calls)
        size += MetadataIngress.ADAPTER.encodedSizeWithTag(2, value.ingress)
        return size
      }

      public override fun encode(writer: ProtoWriter, `value`: Metadata): Unit {
        MetadataCalls.ADAPTER.encodeWithTag(writer, 1, value.calls)
        MetadataIngress.ADAPTER.encodeWithTag(writer, 2, value.ingress)
        writer.writeBytes(value.unknownFields)
      }

      public override fun encode(writer: ReverseProtoWriter, `value`: Metadata): Unit {
        writer.writeBytes(value.unknownFields)
        MetadataIngress.ADAPTER.encodeWithTag(writer, 2, value.ingress)
        MetadataCalls.ADAPTER.encodeWithTag(writer, 1, value.calls)
      }

      public override fun decode(reader: ProtoReader): Metadata {
        var calls: MetadataCalls? = null
        var ingress: MetadataIngress? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> calls = MetadataCalls.ADAPTER.decode(reader)
            2 -> ingress = MetadataIngress.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Metadata(
          calls = calls,
          ingress = ingress,
          unknownFields = unknownFields
        )
      }

      public override fun redact(`value`: Metadata): Metadata = value.copy(
        calls = value.calls?.let(MetadataCalls.ADAPTER::redact),
        ingress = value.ingress?.let(MetadataIngress.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
