_help:
  @just -l

dep-update:
    helm dep update .

set-version version:
    @echo "Setting version to {{version}}"
    yq -i  '.version="{{version}}",.appVersion="{{version}}"' Chart.yaml

package:
    helm lint .
    helm package -u . -d output

publish repo version:
    helm push output/ftl-chart-{{version}}.tgz {{repo}}

release repo version:
    just set-version {{version}}
    just package
    just publish {{repo}} {{version}}