# Create the runtime image.
FROM ubuntu:24.04

WORKDIR /root/

COPY docker-build/ftl-runner .
COPY docker-build/ftl .
RUN mkdir deployments

EXPOSE 8894

ENV FTL_ENDPOINT="http://host.docker.internal:8892"
ENV FTL_RUNNER_BIND="http://0.0.0.0:8893"

CMD ["/root/ftl-runner", "--deployment-dir=deployments"]
