FROM ubuntu:24.04

WORKDIR /root/

#this image does not have a JRE, only test golang on kube

COPY docker-build/ftl-runner .
COPY docker-build/ftl .
RUN mkdir deployments

EXPOSE 8894

ENV FTL_ENDPOINT="http://host.docker.internal:8892"
ENV FTL_RUNNER_BIND="http://0.0.0.0:8893"
ENV FTL_RUNNER_ADVERTISE="http://127.0.0.1:8893"

CMD ["/root/ftl-runner",  "--deployment-dir=deployments"]
