FROM ubuntu:24.04

WORKDIR /root/

COPY docker-build/ftl-controller .
COPY docker-build/ftl-initdb .
COPY docker-build/ftl .
RUN mkdir deployments

EXPOSE 8891
EXPOSE 8892

ENV FTL_CONTROLLER_BIND="http://0.0.0.0:8892"
ENV FTL_CONTROLLER_ADVERTISE="http://127.0.0.1:8892"
ENV FTL_CONTROLLER_CONSOLE_URL="*"
ENV FTL_CONTROLLER_DSN="postgres://host.docker.internal/ftl?sslmode=disable&user=postgres&password=secret"

CMD ["/root/ftl-controller"]
