# Huge hack, we want the JVM and same runtime environment as the runner
# So we just take the latest published runner image and copy the JDK from it
FROM ftl0/ftl-runner-jvm:latest AS jdk
# Create the runtime image.
FROM ubuntu:24.04

WORKDIR /root/
ENV PATH="/root/jdk/bin:$PATH"
ENV JAVA_HOME="/root/jdk"
COPY --from=jdk /root/jdk/ /root/jdk/

COPY docker-build/ftl-runner .
COPY docker-build/ftl .
RUN mkdir deployments

EXPOSE 8894

ENV FTL_ENDPOINT="http://host.docker.internal:8892"
ENV FTL_RUNNER_BIND="http://0.0.0.0:8893"

CMD ["/root/ftl-runner", "--deployment-dir=deployments"]
