FROM ubuntu:24.04

WORKDIR /root/

COPY docker-build/ftl-provisioner .
COPY docker-build/ftl-provisioner-cloudformation /plugins/
COPY docker-build/ftl .
EXPOSE 8893
# Temp hack, this should be a configmap
ENV FTL_PROVISIONER_PLUGIN_CONFIG_FILE="/config/config.toml"
ENV PATH="$PATH:/plugins/"

CMD ["/root/ftl-provisioner"]
