resources:
  - db-create
  - db-migrate
  - ftl-controller
  - ftl-runner
images:
  - name: ftl0/ftl-controller
    newName: ftl0/ftl-controller
    newTag: latest
  - name: ftl0/ftl-runner
    newName: ftl0/ftl-runner
    newTag: latest
