fullnameOverride: "ftl"
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
controller:
  image:
    repository: "ftl:5000/ftl-controller"
    tag: "latest"
    pullPolicy: Always
  service:
    ports:
      - name: "http-8892"
        port: 8892
  ingressService:
    ports:
      - name: "http-8891"
        port: 8891
  podAnnotations:
    proxy.istio.io/config: |
      holdApplicationUntilProxyStarts: true
    sidecar.istio.io/logLevel: "debug"

runner:
  podAnnotations:
    proxy.istio.io/config: |
      holdApplicationUntilProxyStarts: true
    sidecar.istio.io/logLevel: "debug"

provisioner:
  enabled: true
  image:
    repository: "ftl:5000/ftl-provisioner"
    tag: "latest"
    pullPolicy: Always
  service:
    ports:
      - name: "http-8893"
        port: 8893
istio:
  enabled: true

