fullnameOverride: "ftl"
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
controller:
  service:
    ports:
      - name: "http-8892"
        port: 8892
  ingressService:
    ports:
      - name: "http-8891"
        port: 8891
provisioner:
  enabled: true
  image:
    repository: "ftl:5000/ftl-provisioner"
    tag: "latest"
  service:
    ports:
      - name: "http-8893"
        port: 8893
istio:
  enabled: true
