fullnameOverride: "ftl"
ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik
controller:
  image:
    repository: "ftl:5000/ftl"
    tag: "ftl-controller"
    pullPolicy: Always
  service:
    ports:
      - name: "http-8892"
        port: 8892
  ingressService:
    ports:
      - name: "http-8891"
        port: 8891


provisioner:
  enabled: false
  image:
    repository: "ftl:5000/ftl"
    tag: "ftl-provisioner"
    pullPolicy: Always
  service:
    ports:
      - name: "http"
        port: 8893
istio:
  enabled: true

