// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/console/v1/console.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.console.v1;

public interface StreamModulesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.block.ftl.console.v1.StreamModulesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xyz.block.ftl.console.v1.Module modules = 1 [json_name = "modules"];</code>
   */
  java.util.List<xyz.block.ftl.console.v1.Module> 
      getModulesList();
  /**
   * <code>repeated .xyz.block.ftl.console.v1.Module modules = 1 [json_name = "modules"];</code>
   */
  xyz.block.ftl.console.v1.Module getModules(int index);
  /**
   * <code>repeated .xyz.block.ftl.console.v1.Module modules = 1 [json_name = "modules"];</code>
   */
  int getModulesCount();
  /**
   * <code>repeated .xyz.block.ftl.console.v1.Module modules = 1 [json_name = "modules"];</code>
   */
  java.util.List<? extends xyz.block.ftl.console.v1.ModuleOrBuilder> 
      getModulesOrBuilderList();
  /**
   * <code>repeated .xyz.block.ftl.console.v1.Module modules = 1 [json_name = "modules"];</code>
   */
  xyz.block.ftl.console.v1.ModuleOrBuilder getModulesOrBuilder(
      int index);

  /**
   * <code>.xyz.block.ftl.console.v1.Topology topology = 2 [json_name = "topology"];</code>
   * @return Whether the topology field is set.
   */
  boolean hasTopology();
  /**
   * <code>.xyz.block.ftl.console.v1.Topology topology = 2 [json_name = "topology"];</code>
   * @return The topology.
   */
  xyz.block.ftl.console.v1.Topology getTopology();
  /**
   * <code>.xyz.block.ftl.console.v1.Topology topology = 2 [json_name = "topology"];</code>
   */
  xyz.block.ftl.console.v1.TopologyOrBuilder getTopologyOrBuilder();
}
