// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/schema/v1/schema.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.schema.v1;

/**
 * Protobuf type {@code xyz.block.ftl.schema.v1.IngressPathComponent}
 */
public final class IngressPathComponent extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:xyz.block.ftl.schema.v1.IngressPathComponent)
    IngressPathComponentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      IngressPathComponent.class.getName());
  }
  // Use IngressPathComponent.newBuilder() to construct.
  private IngressPathComponent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private IngressPathComponent() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_IngressPathComponent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_IngressPathComponent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            xyz.block.ftl.schema.v1.IngressPathComponent.class, xyz.block.ftl.schema.v1.IngressPathComponent.Builder.class);
  }

  private int valueCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    INGRESS_PATH_LITERAL(1),
    INGRESS_PATH_PARAMETER(2),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 1: return INGRESS_PATH_LITERAL;
        case 2: return INGRESS_PATH_PARAMETER;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  public static final int INGRESS_PATH_LITERAL_FIELD_NUMBER = 1;
  /**
   * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
   * @return Whether the ingressPathLiteral field is set.
   */
  @java.lang.Override
  public boolean hasIngressPathLiteral() {
    return valueCase_ == 1;
  }
  /**
   * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
   * @return The ingressPathLiteral.
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.IngressPathLiteral getIngressPathLiteral() {
    if (valueCase_ == 1) {
       return (xyz.block.ftl.schema.v1.IngressPathLiteral) value_;
    }
    return xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance();
  }
  /**
   * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.IngressPathLiteralOrBuilder getIngressPathLiteralOrBuilder() {
    if (valueCase_ == 1) {
       return (xyz.block.ftl.schema.v1.IngressPathLiteral) value_;
    }
    return xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance();
  }

  public static final int INGRESS_PATH_PARAMETER_FIELD_NUMBER = 2;
  /**
   * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
   * @return Whether the ingressPathParameter field is set.
   */
  @java.lang.Override
  public boolean hasIngressPathParameter() {
    return valueCase_ == 2;
  }
  /**
   * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
   * @return The ingressPathParameter.
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.IngressPathParameter getIngressPathParameter() {
    if (valueCase_ == 2) {
       return (xyz.block.ftl.schema.v1.IngressPathParameter) value_;
    }
    return xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance();
  }
  /**
   * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.IngressPathParameterOrBuilder getIngressPathParameterOrBuilder() {
    if (valueCase_ == 2) {
       return (xyz.block.ftl.schema.v1.IngressPathParameter) value_;
    }
    return xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (valueCase_ == 1) {
      output.writeMessage(1, (xyz.block.ftl.schema.v1.IngressPathLiteral) value_);
    }
    if (valueCase_ == 2) {
      output.writeMessage(2, (xyz.block.ftl.schema.v1.IngressPathParameter) value_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (valueCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (xyz.block.ftl.schema.v1.IngressPathLiteral) value_);
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (xyz.block.ftl.schema.v1.IngressPathParameter) value_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof xyz.block.ftl.schema.v1.IngressPathComponent)) {
      return super.equals(obj);
    }
    xyz.block.ftl.schema.v1.IngressPathComponent other = (xyz.block.ftl.schema.v1.IngressPathComponent) obj;

    if (!getValueCase().equals(other.getValueCase())) return false;
    switch (valueCase_) {
      case 1:
        if (!getIngressPathLiteral()
            .equals(other.getIngressPathLiteral())) return false;
        break;
      case 2:
        if (!getIngressPathParameter()
            .equals(other.getIngressPathParameter())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (valueCase_) {
      case 1:
        hash = (37 * hash) + INGRESS_PATH_LITERAL_FIELD_NUMBER;
        hash = (53 * hash) + getIngressPathLiteral().hashCode();
        break;
      case 2:
        hash = (37 * hash) + INGRESS_PATH_PARAMETER_FIELD_NUMBER;
        hash = (53 * hash) + getIngressPathParameter().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static xyz.block.ftl.schema.v1.IngressPathComponent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static xyz.block.ftl.schema.v1.IngressPathComponent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static xyz.block.ftl.schema.v1.IngressPathComponent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(xyz.block.ftl.schema.v1.IngressPathComponent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xyz.block.ftl.schema.v1.IngressPathComponent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xyz.block.ftl.schema.v1.IngressPathComponent)
      xyz.block.ftl.schema.v1.IngressPathComponentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_IngressPathComponent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_IngressPathComponent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.block.ftl.schema.v1.IngressPathComponent.class, xyz.block.ftl.schema.v1.IngressPathComponent.Builder.class);
    }

    // Construct using xyz.block.ftl.schema.v1.IngressPathComponent.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (ingressPathLiteralBuilder_ != null) {
        ingressPathLiteralBuilder_.clear();
      }
      if (ingressPathParameterBuilder_ != null) {
        ingressPathParameterBuilder_.clear();
      }
      valueCase_ = 0;
      value_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_IngressPathComponent_descriptor;
    }

    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathComponent getDefaultInstanceForType() {
      return xyz.block.ftl.schema.v1.IngressPathComponent.getDefaultInstance();
    }

    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathComponent build() {
      xyz.block.ftl.schema.v1.IngressPathComponent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathComponent buildPartial() {
      xyz.block.ftl.schema.v1.IngressPathComponent result = new xyz.block.ftl.schema.v1.IngressPathComponent(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(xyz.block.ftl.schema.v1.IngressPathComponent result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(xyz.block.ftl.schema.v1.IngressPathComponent result) {
      result.valueCase_ = valueCase_;
      result.value_ = this.value_;
      if (valueCase_ == 1 &&
          ingressPathLiteralBuilder_ != null) {
        result.value_ = ingressPathLiteralBuilder_.build();
      }
      if (valueCase_ == 2 &&
          ingressPathParameterBuilder_ != null) {
        result.value_ = ingressPathParameterBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof xyz.block.ftl.schema.v1.IngressPathComponent) {
        return mergeFrom((xyz.block.ftl.schema.v1.IngressPathComponent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(xyz.block.ftl.schema.v1.IngressPathComponent other) {
      if (other == xyz.block.ftl.schema.v1.IngressPathComponent.getDefaultInstance()) return this;
      switch (other.getValueCase()) {
        case INGRESS_PATH_LITERAL: {
          mergeIngressPathLiteral(other.getIngressPathLiteral());
          break;
        }
        case INGRESS_PATH_PARAMETER: {
          mergeIngressPathParameter(other.getIngressPathParameter());
          break;
        }
        case VALUE_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getIngressPathLiteralFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getIngressPathParameterFieldBuilder().getBuilder(),
                  extensionRegistry);
              valueCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int valueCase_ = 0;
    private java.lang.Object value_;
    public ValueCase
        getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public Builder clearValue() {
      valueCase_ = 0;
      value_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.IngressPathLiteral, xyz.block.ftl.schema.v1.IngressPathLiteral.Builder, xyz.block.ftl.schema.v1.IngressPathLiteralOrBuilder> ingressPathLiteralBuilder_;
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     * @return Whether the ingressPathLiteral field is set.
     */
    @java.lang.Override
    public boolean hasIngressPathLiteral() {
      return valueCase_ == 1;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     * @return The ingressPathLiteral.
     */
    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathLiteral getIngressPathLiteral() {
      if (ingressPathLiteralBuilder_ == null) {
        if (valueCase_ == 1) {
          return (xyz.block.ftl.schema.v1.IngressPathLiteral) value_;
        }
        return xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance();
      } else {
        if (valueCase_ == 1) {
          return ingressPathLiteralBuilder_.getMessage();
        }
        return xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance();
      }
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    public Builder setIngressPathLiteral(xyz.block.ftl.schema.v1.IngressPathLiteral value) {
      if (ingressPathLiteralBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        ingressPathLiteralBuilder_.setMessage(value);
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    public Builder setIngressPathLiteral(
        xyz.block.ftl.schema.v1.IngressPathLiteral.Builder builderForValue) {
      if (ingressPathLiteralBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        ingressPathLiteralBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    public Builder mergeIngressPathLiteral(xyz.block.ftl.schema.v1.IngressPathLiteral value) {
      if (ingressPathLiteralBuilder_ == null) {
        if (valueCase_ == 1 &&
            value_ != xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance()) {
          value_ = xyz.block.ftl.schema.v1.IngressPathLiteral.newBuilder((xyz.block.ftl.schema.v1.IngressPathLiteral) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 1) {
          ingressPathLiteralBuilder_.mergeFrom(value);
        } else {
          ingressPathLiteralBuilder_.setMessage(value);
        }
      }
      valueCase_ = 1;
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    public Builder clearIngressPathLiteral() {
      if (ingressPathLiteralBuilder_ == null) {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 1) {
          valueCase_ = 0;
          value_ = null;
        }
        ingressPathLiteralBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    public xyz.block.ftl.schema.v1.IngressPathLiteral.Builder getIngressPathLiteralBuilder() {
      return getIngressPathLiteralFieldBuilder().getBuilder();
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathLiteralOrBuilder getIngressPathLiteralOrBuilder() {
      if ((valueCase_ == 1) && (ingressPathLiteralBuilder_ != null)) {
        return ingressPathLiteralBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 1) {
          return (xyz.block.ftl.schema.v1.IngressPathLiteral) value_;
        }
        return xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance();
      }
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathLiteral ingress_path_literal = 1 [json_name = "ingressPathLiteral"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.IngressPathLiteral, xyz.block.ftl.schema.v1.IngressPathLiteral.Builder, xyz.block.ftl.schema.v1.IngressPathLiteralOrBuilder> 
        getIngressPathLiteralFieldBuilder() {
      if (ingressPathLiteralBuilder_ == null) {
        if (!(valueCase_ == 1)) {
          value_ = xyz.block.ftl.schema.v1.IngressPathLiteral.getDefaultInstance();
        }
        ingressPathLiteralBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            xyz.block.ftl.schema.v1.IngressPathLiteral, xyz.block.ftl.schema.v1.IngressPathLiteral.Builder, xyz.block.ftl.schema.v1.IngressPathLiteralOrBuilder>(
                (xyz.block.ftl.schema.v1.IngressPathLiteral) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 1;
      onChanged();
      return ingressPathLiteralBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.IngressPathParameter, xyz.block.ftl.schema.v1.IngressPathParameter.Builder, xyz.block.ftl.schema.v1.IngressPathParameterOrBuilder> ingressPathParameterBuilder_;
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     * @return Whether the ingressPathParameter field is set.
     */
    @java.lang.Override
    public boolean hasIngressPathParameter() {
      return valueCase_ == 2;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     * @return The ingressPathParameter.
     */
    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathParameter getIngressPathParameter() {
      if (ingressPathParameterBuilder_ == null) {
        if (valueCase_ == 2) {
          return (xyz.block.ftl.schema.v1.IngressPathParameter) value_;
        }
        return xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance();
      } else {
        if (valueCase_ == 2) {
          return ingressPathParameterBuilder_.getMessage();
        }
        return xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance();
      }
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    public Builder setIngressPathParameter(xyz.block.ftl.schema.v1.IngressPathParameter value) {
      if (ingressPathParameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
        onChanged();
      } else {
        ingressPathParameterBuilder_.setMessage(value);
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    public Builder setIngressPathParameter(
        xyz.block.ftl.schema.v1.IngressPathParameter.Builder builderForValue) {
      if (ingressPathParameterBuilder_ == null) {
        value_ = builderForValue.build();
        onChanged();
      } else {
        ingressPathParameterBuilder_.setMessage(builderForValue.build());
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    public Builder mergeIngressPathParameter(xyz.block.ftl.schema.v1.IngressPathParameter value) {
      if (ingressPathParameterBuilder_ == null) {
        if (valueCase_ == 2 &&
            value_ != xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance()) {
          value_ = xyz.block.ftl.schema.v1.IngressPathParameter.newBuilder((xyz.block.ftl.schema.v1.IngressPathParameter) value_)
              .mergeFrom(value).buildPartial();
        } else {
          value_ = value;
        }
        onChanged();
      } else {
        if (valueCase_ == 2) {
          ingressPathParameterBuilder_.mergeFrom(value);
        } else {
          ingressPathParameterBuilder_.setMessage(value);
        }
      }
      valueCase_ = 2;
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    public Builder clearIngressPathParameter() {
      if (ingressPathParameterBuilder_ == null) {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
      } else {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
        }
        ingressPathParameterBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    public xyz.block.ftl.schema.v1.IngressPathParameter.Builder getIngressPathParameterBuilder() {
      return getIngressPathParameterFieldBuilder().getBuilder();
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    @java.lang.Override
    public xyz.block.ftl.schema.v1.IngressPathParameterOrBuilder getIngressPathParameterOrBuilder() {
      if ((valueCase_ == 2) && (ingressPathParameterBuilder_ != null)) {
        return ingressPathParameterBuilder_.getMessageOrBuilder();
      } else {
        if (valueCase_ == 2) {
          return (xyz.block.ftl.schema.v1.IngressPathParameter) value_;
        }
        return xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance();
      }
    }
    /**
     * <code>.xyz.block.ftl.schema.v1.IngressPathParameter ingress_path_parameter = 2 [json_name = "ingressPathParameter"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.IngressPathParameter, xyz.block.ftl.schema.v1.IngressPathParameter.Builder, xyz.block.ftl.schema.v1.IngressPathParameterOrBuilder> 
        getIngressPathParameterFieldBuilder() {
      if (ingressPathParameterBuilder_ == null) {
        if (!(valueCase_ == 2)) {
          value_ = xyz.block.ftl.schema.v1.IngressPathParameter.getDefaultInstance();
        }
        ingressPathParameterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            xyz.block.ftl.schema.v1.IngressPathParameter, xyz.block.ftl.schema.v1.IngressPathParameter.Builder, xyz.block.ftl.schema.v1.IngressPathParameterOrBuilder>(
                (xyz.block.ftl.schema.v1.IngressPathParameter) value_,
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      valueCase_ = 2;
      onChanged();
      return ingressPathParameterBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:xyz.block.ftl.schema.v1.IngressPathComponent)
  }

  // @@protoc_insertion_point(class_scope:xyz.block.ftl.schema.v1.IngressPathComponent)
  private static final xyz.block.ftl.schema.v1.IngressPathComponent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new xyz.block.ftl.schema.v1.IngressPathComponent();
  }

  public static xyz.block.ftl.schema.v1.IngressPathComponent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IngressPathComponent>
      PARSER = new com.google.protobuf.AbstractParser<IngressPathComponent>() {
    @java.lang.Override
    public IngressPathComponent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IngressPathComponent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IngressPathComponent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public xyz.block.ftl.schema.v1.IngressPathComponent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

