// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/schema/v1/schema.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.schema.v1;

/**
 * Protobuf type {@code xyz.block.ftl.schema.v1.MetadataRetry}
 */
public final class MetadataRetry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:xyz.block.ftl.schema.v1.MetadataRetry)
    MetadataRetryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      MetadataRetry.class.getName());
  }
  // Use MetadataRetry.newBuilder() to construct.
  private MetadataRetry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MetadataRetry() {
    minBackoff_ = "";
    maxBackoff_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_MetadataRetry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_MetadataRetry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            xyz.block.ftl.schema.v1.MetadataRetry.class, xyz.block.ftl.schema.v1.MetadataRetry.Builder.class);
  }

  private int bitField0_;
  public static final int POS_FIELD_NUMBER = 1;
  private xyz.block.ftl.schema.v1.Position pos_;
  /**
   * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
   * @return Whether the pos field is set.
   */
  @java.lang.Override
  public boolean hasPos() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
   * @return The pos.
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.Position getPos() {
    return pos_ == null ? xyz.block.ftl.schema.v1.Position.getDefaultInstance() : pos_;
  }
  /**
   * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.PositionOrBuilder getPosOrBuilder() {
    return pos_ == null ? xyz.block.ftl.schema.v1.Position.getDefaultInstance() : pos_;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private long count_ = 0L;
  /**
   * <code>optional int64 count = 2 [json_name = "count"];</code>
   * @return Whether the count field is set.
   */
  @java.lang.Override
  public boolean hasCount() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int64 count = 2 [json_name = "count"];</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }

  public static final int MIN_BACKOFF_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object minBackoff_ = "";
  /**
   * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
   * @return The minBackoff.
   */
  @java.lang.Override
  public java.lang.String getMinBackoff() {
    java.lang.Object ref = minBackoff_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      minBackoff_ = s;
      return s;
    }
  }
  /**
   * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
   * @return The bytes for minBackoff.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMinBackoffBytes() {
    java.lang.Object ref = minBackoff_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      minBackoff_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_BACKOFF_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object maxBackoff_ = "";
  /**
   * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
   * @return The maxBackoff.
   */
  @java.lang.Override
  public java.lang.String getMaxBackoff() {
    java.lang.Object ref = maxBackoff_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      maxBackoff_ = s;
      return s;
    }
  }
  /**
   * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
   * @return The bytes for maxBackoff.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMaxBackoffBytes() {
    java.lang.Object ref = maxBackoff_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      maxBackoff_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATCH_FIELD_NUMBER = 5;
  private xyz.block.ftl.schema.v1.Ref catch_;
  /**
   * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
   * @return Whether the catch field is set.
   */
  @java.lang.Override
  public boolean hasCatch() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
   * @return The catch.
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.Ref getCatch() {
    return catch_ == null ? xyz.block.ftl.schema.v1.Ref.getDefaultInstance() : catch_;
  }
  /**
   * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
   */
  @java.lang.Override
  public xyz.block.ftl.schema.v1.RefOrBuilder getCatchOrBuilder() {
    return catch_ == null ? xyz.block.ftl.schema.v1.Ref.getDefaultInstance() : catch_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPos());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt64(2, count_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(minBackoff_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, minBackoff_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(maxBackoff_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, maxBackoff_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getCatch());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPos());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, count_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(minBackoff_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, minBackoff_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(maxBackoff_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, maxBackoff_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getCatch());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof xyz.block.ftl.schema.v1.MetadataRetry)) {
      return super.equals(obj);
    }
    xyz.block.ftl.schema.v1.MetadataRetry other = (xyz.block.ftl.schema.v1.MetadataRetry) obj;

    if (hasPos() != other.hasPos()) return false;
    if (hasPos()) {
      if (!getPos()
          .equals(other.getPos())) return false;
    }
    if (hasCount() != other.hasCount()) return false;
    if (hasCount()) {
      if (getCount()
          != other.getCount()) return false;
    }
    if (!getMinBackoff()
        .equals(other.getMinBackoff())) return false;
    if (!getMaxBackoff()
        .equals(other.getMaxBackoff())) return false;
    if (hasCatch() != other.hasCatch()) return false;
    if (hasCatch()) {
      if (!getCatch()
          .equals(other.getCatch())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPos()) {
      hash = (37 * hash) + POS_FIELD_NUMBER;
      hash = (53 * hash) + getPos().hashCode();
    }
    if (hasCount()) {
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCount());
    }
    hash = (37 * hash) + MIN_BACKOFF_FIELD_NUMBER;
    hash = (53 * hash) + getMinBackoff().hashCode();
    hash = (37 * hash) + MAX_BACKOFF_FIELD_NUMBER;
    hash = (53 * hash) + getMaxBackoff().hashCode();
    if (hasCatch()) {
      hash = (37 * hash) + CATCH_FIELD_NUMBER;
      hash = (53 * hash) + getCatch().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static xyz.block.ftl.schema.v1.MetadataRetry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static xyz.block.ftl.schema.v1.MetadataRetry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static xyz.block.ftl.schema.v1.MetadataRetry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(xyz.block.ftl.schema.v1.MetadataRetry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code xyz.block.ftl.schema.v1.MetadataRetry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:xyz.block.ftl.schema.v1.MetadataRetry)
      xyz.block.ftl.schema.v1.MetadataRetryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_MetadataRetry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_MetadataRetry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              xyz.block.ftl.schema.v1.MetadataRetry.class, xyz.block.ftl.schema.v1.MetadataRetry.Builder.class);
    }

    // Construct using xyz.block.ftl.schema.v1.MetadataRetry.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getPosFieldBuilder();
        getCatchFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pos_ = null;
      if (posBuilder_ != null) {
        posBuilder_.dispose();
        posBuilder_ = null;
      }
      count_ = 0L;
      minBackoff_ = "";
      maxBackoff_ = "";
      catch_ = null;
      if (catchBuilder_ != null) {
        catchBuilder_.dispose();
        catchBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return xyz.block.ftl.schema.v1.SchemaOuterClass.internal_static_xyz_block_ftl_schema_v1_MetadataRetry_descriptor;
    }

    @java.lang.Override
    public xyz.block.ftl.schema.v1.MetadataRetry getDefaultInstanceForType() {
      return xyz.block.ftl.schema.v1.MetadataRetry.getDefaultInstance();
    }

    @java.lang.Override
    public xyz.block.ftl.schema.v1.MetadataRetry build() {
      xyz.block.ftl.schema.v1.MetadataRetry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public xyz.block.ftl.schema.v1.MetadataRetry buildPartial() {
      xyz.block.ftl.schema.v1.MetadataRetry result = new xyz.block.ftl.schema.v1.MetadataRetry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(xyz.block.ftl.schema.v1.MetadataRetry result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pos_ = posBuilder_ == null
            ? pos_
            : posBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.count_ = count_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minBackoff_ = minBackoff_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxBackoff_ = maxBackoff_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.catch_ = catchBuilder_ == null
            ? catch_
            : catchBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof xyz.block.ftl.schema.v1.MetadataRetry) {
        return mergeFrom((xyz.block.ftl.schema.v1.MetadataRetry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(xyz.block.ftl.schema.v1.MetadataRetry other) {
      if (other == xyz.block.ftl.schema.v1.MetadataRetry.getDefaultInstance()) return this;
      if (other.hasPos()) {
        mergePos(other.getPos());
      }
      if (other.hasCount()) {
        setCount(other.getCount());
      }
      if (!other.getMinBackoff().isEmpty()) {
        minBackoff_ = other.minBackoff_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getMaxBackoff().isEmpty()) {
        maxBackoff_ = other.maxBackoff_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasCatch()) {
        mergeCatch(other.getCatch());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPosFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              count_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              minBackoff_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              maxBackoff_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getCatchFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private xyz.block.ftl.schema.v1.Position pos_;
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.Position, xyz.block.ftl.schema.v1.Position.Builder, xyz.block.ftl.schema.v1.PositionOrBuilder> posBuilder_;
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     * @return Whether the pos field is set.
     */
    public boolean hasPos() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     * @return The pos.
     */
    public xyz.block.ftl.schema.v1.Position getPos() {
      if (posBuilder_ == null) {
        return pos_ == null ? xyz.block.ftl.schema.v1.Position.getDefaultInstance() : pos_;
      } else {
        return posBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    public Builder setPos(xyz.block.ftl.schema.v1.Position value) {
      if (posBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pos_ = value;
      } else {
        posBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    public Builder setPos(
        xyz.block.ftl.schema.v1.Position.Builder builderForValue) {
      if (posBuilder_ == null) {
        pos_ = builderForValue.build();
      } else {
        posBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    public Builder mergePos(xyz.block.ftl.schema.v1.Position value) {
      if (posBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          pos_ != null &&
          pos_ != xyz.block.ftl.schema.v1.Position.getDefaultInstance()) {
          getPosBuilder().mergeFrom(value);
        } else {
          pos_ = value;
        }
      } else {
        posBuilder_.mergeFrom(value);
      }
      if (pos_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    public Builder clearPos() {
      bitField0_ = (bitField0_ & ~0x00000001);
      pos_ = null;
      if (posBuilder_ != null) {
        posBuilder_.dispose();
        posBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    public xyz.block.ftl.schema.v1.Position.Builder getPosBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getPosFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    public xyz.block.ftl.schema.v1.PositionOrBuilder getPosOrBuilder() {
      if (posBuilder_ != null) {
        return posBuilder_.getMessageOrBuilder();
      } else {
        return pos_ == null ?
            xyz.block.ftl.schema.v1.Position.getDefaultInstance() : pos_;
      }
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Position pos = 1 [json_name = "pos"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.Position, xyz.block.ftl.schema.v1.Position.Builder, xyz.block.ftl.schema.v1.PositionOrBuilder> 
        getPosFieldBuilder() {
      if (posBuilder_ == null) {
        posBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            xyz.block.ftl.schema.v1.Position, xyz.block.ftl.schema.v1.Position.Builder, xyz.block.ftl.schema.v1.PositionOrBuilder>(
                getPos(),
                getParentForChildren(),
                isClean());
        pos_ = null;
      }
      return posBuilder_;
    }

    private long count_ ;
    /**
     * <code>optional int64 count = 2 [json_name = "count"];</code>
     * @return Whether the count field is set.
     */
    @java.lang.Override
    public boolean hasCount() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int64 count = 2 [json_name = "count"];</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return count_;
    }
    /**
     * <code>optional int64 count = 2 [json_name = "count"];</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {

      count_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 count = 2 [json_name = "count"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      count_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object minBackoff_ = "";
    /**
     * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
     * @return The minBackoff.
     */
    public java.lang.String getMinBackoff() {
      java.lang.Object ref = minBackoff_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        minBackoff_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
     * @return The bytes for minBackoff.
     */
    public com.google.protobuf.ByteString
        getMinBackoffBytes() {
      java.lang.Object ref = minBackoff_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minBackoff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
     * @param value The minBackoff to set.
     * @return This builder for chaining.
     */
    public Builder setMinBackoff(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      minBackoff_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMinBackoff() {
      minBackoff_ = getDefaultInstance().getMinBackoff();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string min_backoff = 3 [json_name = "minBackoff"];</code>
     * @param value The bytes for minBackoff to set.
     * @return This builder for chaining.
     */
    public Builder setMinBackoffBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      minBackoff_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object maxBackoff_ = "";
    /**
     * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
     * @return The maxBackoff.
     */
    public java.lang.String getMaxBackoff() {
      java.lang.Object ref = maxBackoff_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        maxBackoff_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
     * @return The bytes for maxBackoff.
     */
    public com.google.protobuf.ByteString
        getMaxBackoffBytes() {
      java.lang.Object ref = maxBackoff_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        maxBackoff_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
     * @param value The maxBackoff to set.
     * @return This builder for chaining.
     */
    public Builder setMaxBackoff(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      maxBackoff_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxBackoff() {
      maxBackoff_ = getDefaultInstance().getMaxBackoff();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string max_backoff = 4 [json_name = "maxBackoff"];</code>
     * @param value The bytes for maxBackoff to set.
     * @return This builder for chaining.
     */
    public Builder setMaxBackoffBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      maxBackoff_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private xyz.block.ftl.schema.v1.Ref catch_;
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.Ref, xyz.block.ftl.schema.v1.Ref.Builder, xyz.block.ftl.schema.v1.RefOrBuilder> catchBuilder_;
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     * @return Whether the catch field is set.
     */
    public boolean hasCatch() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     * @return The catch.
     */
    public xyz.block.ftl.schema.v1.Ref getCatch() {
      if (catchBuilder_ == null) {
        return catch_ == null ? xyz.block.ftl.schema.v1.Ref.getDefaultInstance() : catch_;
      } else {
        return catchBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    public Builder setCatch(xyz.block.ftl.schema.v1.Ref value) {
      if (catchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        catch_ = value;
      } else {
        catchBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    public Builder setCatch(
        xyz.block.ftl.schema.v1.Ref.Builder builderForValue) {
      if (catchBuilder_ == null) {
        catch_ = builderForValue.build();
      } else {
        catchBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    public Builder mergeCatch(xyz.block.ftl.schema.v1.Ref value) {
      if (catchBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          catch_ != null &&
          catch_ != xyz.block.ftl.schema.v1.Ref.getDefaultInstance()) {
          getCatchBuilder().mergeFrom(value);
        } else {
          catch_ = value;
        }
      } else {
        catchBuilder_.mergeFrom(value);
      }
      if (catch_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    public Builder clearCatch() {
      bitField0_ = (bitField0_ & ~0x00000010);
      catch_ = null;
      if (catchBuilder_ != null) {
        catchBuilder_.dispose();
        catchBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    public xyz.block.ftl.schema.v1.Ref.Builder getCatchBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getCatchFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    public xyz.block.ftl.schema.v1.RefOrBuilder getCatchOrBuilder() {
      if (catchBuilder_ != null) {
        return catchBuilder_.getMessageOrBuilder();
      } else {
        return catch_ == null ?
            xyz.block.ftl.schema.v1.Ref.getDefaultInstance() : catch_;
      }
    }
    /**
     * <code>optional .xyz.block.ftl.schema.v1.Ref catch = 5 [json_name = "catch"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        xyz.block.ftl.schema.v1.Ref, xyz.block.ftl.schema.v1.Ref.Builder, xyz.block.ftl.schema.v1.RefOrBuilder> 
        getCatchFieldBuilder() {
      if (catchBuilder_ == null) {
        catchBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            xyz.block.ftl.schema.v1.Ref, xyz.block.ftl.schema.v1.Ref.Builder, xyz.block.ftl.schema.v1.RefOrBuilder>(
                getCatch(),
                getParentForChildren(),
                isClean());
        catch_ = null;
      }
      return catchBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:xyz.block.ftl.schema.v1.MetadataRetry)
  }

  // @@protoc_insertion_point(class_scope:xyz.block.ftl.schema.v1.MetadataRetry)
  private static final xyz.block.ftl.schema.v1.MetadataRetry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new xyz.block.ftl.schema.v1.MetadataRetry();
  }

  public static xyz.block.ftl.schema.v1.MetadataRetry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MetadataRetry>
      PARSER = new com.google.protobuf.AbstractParser<MetadataRetry>() {
    @java.lang.Override
    public MetadataRetry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetadataRetry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetadataRetry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public xyz.block.ftl.schema.v1.MetadataRetry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

