// Code generated by FTL. DO NOT EDIT.
package {{.Name}}
{{if .LocalSumTypes }}
import "github.com/TBD54566975/ftl/go-runtime/ftl/reflection"

func init() {
	reflection.Register(
{{- range .LocalSumTypes}}
		reflection.SumType[{{.Discriminator}}](
			{{- range .Variants}}
			*new({{.Name}}),
			{{- end}}
		),
{{- end}}
	)
}
{{- end}}
