// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: xyz/block/ftl/v1/schema/runtime.proto

package pschema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OFFLINE  Status = 0
	Status_STARTING Status = 1
	Status_ONLINE   Status = 2
	Status_STOPPING Status = 3
	Status_STOPPED  Status = 4
	Status_ERRORED  Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OFFLINE",
		1: "STARTING",
		2: "ONLINE",
		3: "STOPPING",
		4: "STOPPED",
		5: "ERRORED",
	}
	Status_value = map[string]int32{
		"OFFLINE":  0,
		"STARTING": 1,
		"ONLINE":   2,
		"STOPPING": 3,
		"STOPPED":  4,
		"ERRORED":  5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_xyz_block_ftl_v1_schema_runtime_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_xyz_block_ftl_v1_schema_runtime_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schema_runtime_proto_rawDescGZIP(), []int{0}
}

type ModuleRuntime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Language   string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *ModuleRuntime) Reset() {
	*x = ModuleRuntime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleRuntime) ProtoMessage() {}

func (x *ModuleRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleRuntime.ProtoReflect.Descriptor instead.
func (*ModuleRuntime) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schema_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleRuntime) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *ModuleRuntime) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type VerbRuntime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreateTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	StartTime  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Status     Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=xyz.block.ftl.v1.schema.Status" json:"status,omitempty"`
}

func (x *VerbRuntime) Reset() {
	*x = VerbRuntime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerbRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerbRuntime) ProtoMessage() {}

func (x *VerbRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerbRuntime.ProtoReflect.Descriptor instead.
func (*VerbRuntime) Descriptor() ([]byte, []int) {
	return file_xyz_block_ftl_v1_schema_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *VerbRuntime) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *VerbRuntime) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *VerbRuntime) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_OFFLINE
}

var File_xyz_block_ftl_v1_schema_runtime_proto protoreflect.FileDescriptor

var file_xyz_block_ftl_v1_schema_runtime_proto_rawDesc = []byte{
	0x0a, 0x25, 0x78, 0x79, 0x7a, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x66, 0x74, 0x6c, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x78, 0x79, 0x7a, 0x2e, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x66, 0x74, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x68, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22, 0xbe, 0x01, 0x0a, 0x0b,
	0x56, 0x65, 0x72, 0x62, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x78, 0x79, 0x7a, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e,
	0x66, 0x74, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x57, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x54, 0x4f, 0x50, 0x50, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53,
	0x54, 0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x45, 0x44, 0x10, 0x05, 0x42, 0x45, 0x50, 0x01, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x42, 0x44, 0x35, 0x34, 0x35, 0x36, 0x36, 0x39, 0x37,
	0x35, 0x2f, 0x66, 0x74, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x78, 0x79, 0x7a,
	0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x66, 0x74, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x3b, 0x70, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xyz_block_ftl_v1_schema_runtime_proto_rawDescOnce sync.Once
	file_xyz_block_ftl_v1_schema_runtime_proto_rawDescData = file_xyz_block_ftl_v1_schema_runtime_proto_rawDesc
)

func file_xyz_block_ftl_v1_schema_runtime_proto_rawDescGZIP() []byte {
	file_xyz_block_ftl_v1_schema_runtime_proto_rawDescOnce.Do(func() {
		file_xyz_block_ftl_v1_schema_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(file_xyz_block_ftl_v1_schema_runtime_proto_rawDescData)
	})
	return file_xyz_block_ftl_v1_schema_runtime_proto_rawDescData
}

var file_xyz_block_ftl_v1_schema_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xyz_block_ftl_v1_schema_runtime_proto_goTypes = []interface{}{
	(Status)(0),                   // 0: xyz.block.ftl.v1.schema.Status
	(*ModuleRuntime)(nil),         // 1: xyz.block.ftl.v1.schema.ModuleRuntime
	(*VerbRuntime)(nil),           // 2: xyz.block.ftl.v1.schema.VerbRuntime
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_xyz_block_ftl_v1_schema_runtime_proto_depIdxs = []int32{
	3, // 0: xyz.block.ftl.v1.schema.ModuleRuntime.create_time:type_name -> google.protobuf.Timestamp
	3, // 1: xyz.block.ftl.v1.schema.VerbRuntime.create_time:type_name -> google.protobuf.Timestamp
	3, // 2: xyz.block.ftl.v1.schema.VerbRuntime.start_time:type_name -> google.protobuf.Timestamp
	0, // 3: xyz.block.ftl.v1.schema.VerbRuntime.status:type_name -> xyz.block.ftl.v1.schema.Status
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_xyz_block_ftl_v1_schema_runtime_proto_init() }
func file_xyz_block_ftl_v1_schema_runtime_proto_init() {
	if File_xyz_block_ftl_v1_schema_runtime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleRuntime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerbRuntime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xyz_block_ftl_v1_schema_runtime_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xyz_block_ftl_v1_schema_runtime_proto_goTypes,
		DependencyIndexes: file_xyz_block_ftl_v1_schema_runtime_proto_depIdxs,
		EnumInfos:         file_xyz_block_ftl_v1_schema_runtime_proto_enumTypes,
		MessageInfos:      file_xyz_block_ftl_v1_schema_runtime_proto_msgTypes,
	}.Build()
	File_xyz_block_ftl_v1_schema_runtime_proto = out.File
	file_xyz_block_ftl_v1_schema_runtime_proto_rawDesc = nil
	file_xyz_block_ftl_v1_schema_runtime_proto_goTypes = nil
	file_xyz_block_ftl_v1_schema_runtime_proto_depIdxs = nil
}
