// tonic::include_proto!("xyz.block.ftl.v1.schema");
// Generated by [`prost-build`]
include!(concat!(env!("OUT_DIR"), "/xyz.block.ftl.v1.schema.rs"));
// Generated by [`pbjson-build`]
include!(concat!(
    env!("OUT_DIR"),
    "/xyz.block.ftl.v1.schema.serde.rs"
));
