name: Build Cache
description: Cache builds
runs:
  using: "composite"
  steps:
    - name: Cache Go Modules
      id: cache-go-modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-{{ hashFiles('**/go.sum') }}-go
    - name: Cache Maven Modules
      id: cache-maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-{{ hashFiles('**/pom.xml') }}-maven
    - name: Populate Cache
      id: populate-cache
      uses: ./.github/actions/populate-cache

