name: Build Cache
description: Cache builds
runs:
  using: "composite"
  # Make sure to keep these cache entries in sync with those in writecache.yml
  steps:
    - id: find-go-build-cache
      shell: bash
      run: echo "cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
    - name: Cache Docker Images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('docker-compose.yml') }}
        read-only: true
    - name: Restore Go Modules Cache
      id: cache-go-modules
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/go/pkg/mod
          ${{ steps.find-go-build-cache.outputs.cache }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          ${{ runner.os }}-
    - name: Restore Maven Modules Cache
      id: cache-maven
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          ${{ runner.os }}-maven-
    - name: Restore pnpm Cache
      id: cache-pnpm
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-



