name: Build Cache
description: Cache builds
runs:
  using: "composite"
  # Make sure to keep these cache entries in sync with those in writecache.yml
  steps:
    - name: Restore Go Modules Cache
      id: cache-go-modules
      uses: actions/cache/restore@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go
    - name: Restore Maven Modules Cache
      id: cache-maven
      uses: actions/cache/restore@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven

