#!/bin/bash
set -euo pipefail

old_version="$(svu current)"
new_version="$(svu next --force-patch-increment)"

test -z "$GH_TOKEN" && { echo "GH_TOKEN is not set"; exit 1; }

echo "Version updating from ${old_version} to ${new_version}"

gh api -H "Accept: application/vnd.github.v3+json" \
  "/repos/{owner}/{repo}/git/refs" \
  -f ref="refs/tags/${new_version}" \
  -f sha="$(git rev-parse HEAD)"
