#!/bin/bash
set -euo pipefail
ftldir="$(dirname "$0")/.."
name="$(basename "$0")"
dest="${ftldir}/build/devel"
mkdir -p "$dest"
(cd "${ftldir}/cmd/${name}" && "${ftldir}/bin/go" build -ldflags="-s -w -buildid=" -o "$dest/${name}" ./) && exec "$dest/${name}" "$@"
