#!/bin/bash
set -euo pipefail

dir="$(git rev-parse --show-toplevel)/drive-kotlin"

newest() {
  find "$1" -type f ! -path '*/.ftl/*' -print0 | xargs -0 -r ls -1 -t | tail -n +1 | head -1 2> /dev/null
}

cd "$dir"

# Recompile if necessary.
if [ ! -d target -o \( "$(newest ./src)" -nt "$(newest ./target)" \) ]; then
  mvn compile
fi

# This should be different in the production clone
exec mvn exec:exec -Dexec.executable=java -Dexec.args="-classpath %classpath\
  -XX:+AllowEnhancedClassRedefinition -XX:HotswapAgent=fatjar xyz.block.ftl.drive.MainKt"
