#!/bin/bash
set -euo pipefail

top="$(git rev-parse --show-toplevel)"
cd "${top}"


build() {
  bit build/template/ftl/jars/ftl-runtime.jar \
    build/release/ftl-controller \
    build/release/ftl-runner 
}

build

overmind start -f Procfile.nowatch
