#!/bin/bash
set -euo pipefail

tmux \
  set -g mouse on \; \
  new-session 'watchexec -r -e go -- ftl-controller --key C01H5BRT09Y07547SETZ4HWRA09' \; \
  select-layout even-vertical \; \
  split-window 'watchexec -r -e go -- ftl-runner --key R01H5BTS6ABP1EHGZSAGJMBV50A --language go --endpoint http://localhost:8894' \; \
  select-layout even-vertical \; \
  split-window 'watchexec -r -e go -- ftl-runner --key R01H5BTSGKQ8AZ9S22N9N1SM9HV --language go --endpoint http://localhost:8895' \; \
  select-layout even-vertical \; \
  split-window 'watchexec -e yaml -e sql -w protos/xyz/block/ftl/v1 -- make generate' \; \
  select-layout even-vertical
