#!/bin/bash
set -euo pipefail
ftldir="$(dirname "$(readlink -f "$0")")/.."
name="ftl-language-java"
if [ -n "${CI-}" ]; then
  dest="${ftldir}/build/release"
else
  dest="${ftldir}/build/devel"
  mkdir -p "$dest"
  (cd "${ftldir}/jvm-runtime/cmd/ftl-language-java" && "${ftldir}/bin/go" build -ldflags="-s -w -buildid=" -o "$dest/${name}" ./)
fi
exec "$dest/${name}" "$@"