#!/bin/bash
set -euo pipefail

tmux \
  set -g mouse on \; \
  set -g status off \; \
  new-session 'watchexec -r -e go -i "examples/**" -- ftl-controller --key C01H5BRT09Y07547SETZ4HWRA09 --bind http://localhost:8892 || read' \; \
  select-layout even-vertical \; \
  split-window 'watchexec -r -e go -i "examples/**" -- ftl-runner --key R01H5BTS6ABP1EHGZSAGJMBV50A --language go --bind http://localhost:8894 || read' \; \
  select-layout even-vertical \; \
  split-window 'watchexec -r -e go -i "examples/**" -- ftl-runner --key R01H5BTSGKQ8AZ9S22N9N1SM9HV --language go --bind http://localhost:8895 || read' \; \
  select-layout even-vertical \; \
  split-window 'watchexec -e yaml -e sql -e proto -i "examples/**" --debounce 1s -- make generate' \; \
  select-layout even-vertical
