#!/bin/bash
set -euo pipefail
ftldir="$(dirname "$(readlink -f "$0")")/.."
name="ftl-language-python"
dest="${ftldir}/build/devel"
mkdir -p "$dest"
(cd "${ftldir}/python-runtime/cmd" && "${ftldir}/bin/go" build -ldflags="-s -w -buildid=" -o "$dest/${name}" ./) && exec "$dest/${name}" "$@"
