#!/bin/bash
set -euo pipefail

top="$(git rev-parse --show-toplevel)"
cd "${top}"

prepare_template() (
  make build/template/ftl/jars/ftl-runtime.jar
)

build() {
  make console/client/dist/index.html
  go build -o build/release/ftl-controller -tags release ./cmd/ftl-controller
  go build -o build/release/ftl-runner -tags release ./cmd/ftl-runner
}

prepare_template
build

overmind start -f Procfile.nowatch
