#!/bin/bash
set -euo pipefail
export PATH="$PWD/build/release:$PATH"

info() {
  echo -e "\033[1;32m$*\033[0m"
}

error() {
  echo -e "\033[1;31m$*\033[0m"
  exit 1
}

build_release() {
  info "Building release"
  rm -rf build
  make release
}

wipe_database() {
  info "Initialising database"
  ftl-initdb --recreate
}

wait_for() {
  info "Waiting for $1"
  for _ in {1..60}; do
    if eval "$2"; then
      info "Success!"
      return 0
    fi
    sleep 1
  done
  error "Timed out waiting for $1"
}

start_cluster() {
  info "Starting cluster"
  overmind start --procfile Procfile.integration &
  wait_for "cluster to become ready" "ftl status"
  trap "overmind quit" EXIT INT TERM
}

prepare_runner() (
  info "Preparing runner template directory"
  mvn -pl :ftl-generator install
  mkdir -p build/template/ftl/jars build/runner0 build/runner1
  test -r build/template/ftl/jars/ftl-runtime.jar && return 0
  make build/template/ftl/jars/ftl-runtime.jar
)

deploy_echo_kotlin() (
  info "Deploying echo-kotlin"
  cd examples/echo-kotlin
  mvn compile
  ftl deploy target
)

deploy_time_go() (
  info "Deploying time"
  cd examples
  # Pull a supported platforms from the cluster.
  platform="$(ftl status | jq -r '.runners[].labels | "\(.os)-\(.arch)"' | sort | uniq | head -1)"
  ftl-go --os "${platform%-*}" --arch "${platform#*-}" deploy time
)

wait_for_deploys() {
  wait_for "deployments to come up" 'ftl status | jq -r ".routes[].module" | sort | paste -sd " " - | grep -q "echo time"'
}

build_release
wipe_database
prepare_runner
start_cluster

# Cluster is up, start interacting with it.
deploy_time_go
deploy_echo_kotlin

wait_for_deploys

info "Calling echo"
message="$(ftl call echo.echo '{"name": "Alice"}' | jq -r .message)"
[[ "$message" =~ "Hello, Alice! The time is " ]] || error "Unexpected response from echo: $message"
info "Success!"
