services:
  otel-lgtm:
    image: ${FTL_GRAFANA_IMAGE:-grafana/otel-lgtm}
    platform: linux/amd64
    ports:
      - 3000:3000 # Portal Endpoint
      - 9090:9090 # Prometheus
      - ${OTEL_GRPC_PORT:-4317}:4317 # OTLP GRPC Collector
      - ${OTEL_HTTP_PORT:-4318}:4318 # OTLP HTTP Collector
    environment:
      - ENABLE_LOGS_ALL=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

volumes:
  grafana-storage: {}
