services:
  mysql:
    image: mysql:8.4.3
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: ftl
    ports:
      - "${MYSQL_PORT:-13306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=secret"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
