[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
schema = { workspace = true }
server = { workspace = true }

clap = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }