[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
schema = { path = "../schema" }

clap = { version = "4.5.7", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }