// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file xyz/block/ftl/publish/v1/publish.proto (package xyz.block.ftl.publish.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingRequest, PingResponse } from "../../v1/ftl_pb.js";
import { MethodIdempotency, MethodKind } from "@bufbuild/protobuf";
import { PublishEventRequest, PublishEventResponse } from "./publish_pb.js";

/**
 * @generated from service xyz.block.ftl.publish.v1.PublishService
 */
export const PublishService = {
  typeName: "xyz.block.ftl.publish.v1.PublishService",
  methods: {
    /**
     * Ping service for readiness.
     *
     * @generated from rpc xyz.block.ftl.publish.v1.PublishService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
      idempotency: MethodIdempotency.NoSideEffects,
    },
    /**
     * Publish a message to a topic.
     *
     * @generated from rpc xyz.block.ftl.publish.v1.PublishService.PublishEvent
     */
    publishEvent: {
      name: "PublishEvent",
      I: PublishEventRequest,
      O: PublishEventResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

