# Start the FTL backend with hot-reloading
dev:
  ftl dev --allow-origins '*'

gen-mobile:
  ftl schema generate mobile/templates/ online-boutique/mobile/lib/api --watch=5s

gen-web:
  ftl schema generate web/templates/ online-boutique/web/src/api --watch=5s

# Start the example web frontend for online-boutique
web:
  cd web && npm install && npm run dev
