// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/timeline/v1/event.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.timeline.v1;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.block.ftl.timeline.v1.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp"];</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp"];</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1 [json_name = "timestamp"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   * Unique ID for event.
   * </pre>
   *
   * <code>int64 id = 2 [json_name = "id"];</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>.xyz.block.ftl.timeline.v1.LogEvent log = 3 [json_name = "log"];</code>
   * @return Whether the log field is set.
   */
  boolean hasLog();
  /**
   * <code>.xyz.block.ftl.timeline.v1.LogEvent log = 3 [json_name = "log"];</code>
   * @return The log.
   */
  xyz.block.ftl.timeline.v1.LogEvent getLog();
  /**
   * <code>.xyz.block.ftl.timeline.v1.LogEvent log = 3 [json_name = "log"];</code>
   */
  xyz.block.ftl.timeline.v1.LogEventOrBuilder getLogOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.CallEvent call = 4 [json_name = "call"];</code>
   * @return Whether the call field is set.
   */
  boolean hasCall();
  /**
   * <code>.xyz.block.ftl.timeline.v1.CallEvent call = 4 [json_name = "call"];</code>
   * @return The call.
   */
  xyz.block.ftl.timeline.v1.CallEvent getCall();
  /**
   * <code>.xyz.block.ftl.timeline.v1.CallEvent call = 4 [json_name = "call"];</code>
   */
  xyz.block.ftl.timeline.v1.CallEventOrBuilder getCallOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.DeploymentCreatedEvent deployment_created = 5 [json_name = "deploymentCreated"];</code>
   * @return Whether the deploymentCreated field is set.
   */
  boolean hasDeploymentCreated();
  /**
   * <code>.xyz.block.ftl.timeline.v1.DeploymentCreatedEvent deployment_created = 5 [json_name = "deploymentCreated"];</code>
   * @return The deploymentCreated.
   */
  xyz.block.ftl.timeline.v1.DeploymentCreatedEvent getDeploymentCreated();
  /**
   * <code>.xyz.block.ftl.timeline.v1.DeploymentCreatedEvent deployment_created = 5 [json_name = "deploymentCreated"];</code>
   */
  xyz.block.ftl.timeline.v1.DeploymentCreatedEventOrBuilder getDeploymentCreatedOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent deployment_updated = 6 [json_name = "deploymentUpdated"];</code>
   * @return Whether the deploymentUpdated field is set.
   */
  boolean hasDeploymentUpdated();
  /**
   * <code>.xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent deployment_updated = 6 [json_name = "deploymentUpdated"];</code>
   * @return The deploymentUpdated.
   */
  xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent getDeploymentUpdated();
  /**
   * <code>.xyz.block.ftl.timeline.v1.DeploymentUpdatedEvent deployment_updated = 6 [json_name = "deploymentUpdated"];</code>
   */
  xyz.block.ftl.timeline.v1.DeploymentUpdatedEventOrBuilder getDeploymentUpdatedOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.IngressEvent ingress = 7 [json_name = "ingress"];</code>
   * @return Whether the ingress field is set.
   */
  boolean hasIngress();
  /**
   * <code>.xyz.block.ftl.timeline.v1.IngressEvent ingress = 7 [json_name = "ingress"];</code>
   * @return The ingress.
   */
  xyz.block.ftl.timeline.v1.IngressEvent getIngress();
  /**
   * <code>.xyz.block.ftl.timeline.v1.IngressEvent ingress = 7 [json_name = "ingress"];</code>
   */
  xyz.block.ftl.timeline.v1.IngressEventOrBuilder getIngressOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.CronScheduledEvent cron_scheduled = 8 [json_name = "cronScheduled"];</code>
   * @return Whether the cronScheduled field is set.
   */
  boolean hasCronScheduled();
  /**
   * <code>.xyz.block.ftl.timeline.v1.CronScheduledEvent cron_scheduled = 8 [json_name = "cronScheduled"];</code>
   * @return The cronScheduled.
   */
  xyz.block.ftl.timeline.v1.CronScheduledEvent getCronScheduled();
  /**
   * <code>.xyz.block.ftl.timeline.v1.CronScheduledEvent cron_scheduled = 8 [json_name = "cronScheduled"];</code>
   */
  xyz.block.ftl.timeline.v1.CronScheduledEventOrBuilder getCronScheduledOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.AsyncExecuteEvent async_execute = 9 [json_name = "asyncExecute"];</code>
   * @return Whether the asyncExecute field is set.
   */
  boolean hasAsyncExecute();
  /**
   * <code>.xyz.block.ftl.timeline.v1.AsyncExecuteEvent async_execute = 9 [json_name = "asyncExecute"];</code>
   * @return The asyncExecute.
   */
  xyz.block.ftl.timeline.v1.AsyncExecuteEvent getAsyncExecute();
  /**
   * <code>.xyz.block.ftl.timeline.v1.AsyncExecuteEvent async_execute = 9 [json_name = "asyncExecute"];</code>
   */
  xyz.block.ftl.timeline.v1.AsyncExecuteEventOrBuilder getAsyncExecuteOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.PubSubPublishEvent pubsub_publish = 10 [json_name = "pubsubPublish"];</code>
   * @return Whether the pubsubPublish field is set.
   */
  boolean hasPubsubPublish();
  /**
   * <code>.xyz.block.ftl.timeline.v1.PubSubPublishEvent pubsub_publish = 10 [json_name = "pubsubPublish"];</code>
   * @return The pubsubPublish.
   */
  xyz.block.ftl.timeline.v1.PubSubPublishEvent getPubsubPublish();
  /**
   * <code>.xyz.block.ftl.timeline.v1.PubSubPublishEvent pubsub_publish = 10 [json_name = "pubsubPublish"];</code>
   */
  xyz.block.ftl.timeline.v1.PubSubPublishEventOrBuilder getPubsubPublishOrBuilder();

  /**
   * <code>.xyz.block.ftl.timeline.v1.PubSubConsumeEvent pubsub_consume = 11 [json_name = "pubsubConsume"];</code>
   * @return Whether the pubsubConsume field is set.
   */
  boolean hasPubsubConsume();
  /**
   * <code>.xyz.block.ftl.timeline.v1.PubSubConsumeEvent pubsub_consume = 11 [json_name = "pubsubConsume"];</code>
   * @return The pubsubConsume.
   */
  xyz.block.ftl.timeline.v1.PubSubConsumeEvent getPubsubConsume();
  /**
   * <code>.xyz.block.ftl.timeline.v1.PubSubConsumeEvent pubsub_consume = 11 [json_name = "pubsubConsume"];</code>
   */
  xyz.block.ftl.timeline.v1.PubSubConsumeEventOrBuilder getPubsubConsumeOrBuilder();

  xyz.block.ftl.timeline.v1.Event.EntryCase getEntryCase();
}
