// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: xyz/block/ftl/timeline/v1/timeline.proto
// Protobuf Java Version: 4.29.0

package xyz.block.ftl.timeline.v1;

public interface StreamTimelineResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.block.ftl.timeline.v1.StreamTimelineResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .xyz.block.ftl.timeline.v1.Event events = 1 [json_name = "events"];</code>
   */
  java.util.List<xyz.block.ftl.timeline.v1.Event> 
      getEventsList();
  /**
   * <code>repeated .xyz.block.ftl.timeline.v1.Event events = 1 [json_name = "events"];</code>
   */
  xyz.block.ftl.timeline.v1.Event getEvents(int index);
  /**
   * <code>repeated .xyz.block.ftl.timeline.v1.Event events = 1 [json_name = "events"];</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .xyz.block.ftl.timeline.v1.Event events = 1 [json_name = "events"];</code>
   */
  java.util.List<? extends xyz.block.ftl.timeline.v1.EventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .xyz.block.ftl.timeline.v1.Event events = 1 [json_name = "events"];</code>
   */
  xyz.block.ftl.timeline.v1.EventOrBuilder getEventsOrBuilder(
      int index);
}
