apiVersion: v2
name: ftl
description: |
  A Helm chart for Kubernetes that deploys FTL
home: https://github.com/TBD54566975/ftl
version: 0.0.1
appVersion: 0.0.1
dependencies:
  - name: postgresql
    version: 15.5.38
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled