on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-integration
  cancel-in-progress: true
name: Integration
jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Build Cache
        uses: ./.github/actions/build-cache
      - name: Docker Compose
        run: docker compose up -d --wait
      - name: Download Go Modules
        run: go mod download
      - name: Integration tests
        run: go test -v -tags integration ./integration
