on:
  workflow_call:
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-integration
  cancel-in-progress: true
name: Integration
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-tests.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Extract test cases
        id: extract-tests
        run: |
          echo "cases=$(go test -v -list . -tags integration ./integration | grep '^Test' | awk '{print $1}' | cut -d '(' -f1 | tr '\n' ',' | sed 's/,$//')" >> "$GITHUB_OUTPUT"
      - name: Format test matrix
        id: set-tests
        run: |
          IFS=',' read -ra TESTS <<< "${{ steps.extract-tests.outputs.cases }}"
          TEST_JSON=$(printf ',"%s"' "${TESTS[@]}")
          TEST_JSON="[${TEST_JSON:1}]"
          echo "matrix={\"test\": $TEST_JSON}" >> "$GITHUB_OUTPUT"
  integration:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Build Cache
        uses: ./.github/actions/build-cache
      - name: Docker Compose
        run: docker compose up -d --wait
      - name: Download Go Modules
        run: go mod download
      - name: Run ${{ matrix.test }}
        run: go test -v -tags integration -run ${{ matrix.test }} ./integration