on:
  workflow_call:
concurrency:
  group: ${{ github.ref }}-integration
  cancel-in-progress: true
name: Integration
jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Cache Go Modules
        id: cache-go-modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go
      - name: Cache Maven Repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
      - name: Docker Compose
        run: docker compose up -d --wait
      - name: Download Go Modules
        run: go mod download
      - name: Integration tests
        run: go test -v -tags integration ./integration
