on:
  workflow_call:
name: Integration
jobs:
  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      - name: Cache Go Modules
        id: cache-go-modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go
      - name: Docker Compose
        run: docker compose up -d --wait
      - name: Integration tests
        run: integration-tests
