# Hopefully use this for the "required status checks"
name: CI Status Check
on:
  workflow_run:
    workflows: ["CI"]
    branches-ignore: ["main"]
    types:
      - completed
jobs:
  on-success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "CI Passed"
          exit 0
  on-failure:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "CI Failed"
          exit 1
