on:
  push:
    branches:
      - main
name: Publish Snapshots
jobs:
  release-jars:
    name: Release JARs
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Init Hermit
        uses: cashapp/activate-hermit@v1
      # Ideally we'd use Hermit's JDK, but this action creates the correct settings.xml for us.
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: 'ossrh' # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-passphrase: SIGN_KEY_PASS
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          cache: 'maven'
      - name: Publish Snapshot JARs
        run: |
          mvn --batch-mode versions:set -DnewVersion=$(git describe --tags --abbrev=0 | cut -c2-)-SNAPSHOT -DprocessAllModules -DgenerateBackupPoms=false
          mvn -U --batch-mode clean deploy -P snapshot
        env:
          SIGN_KEY_PASS: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GITHUB_TOKEN: ${{ github.token }}