# This name needs to be kept in sync with the workflow_run event in workflow-roadmap.yml
name: Clear triage label when moved to next
on:
  issues:
    types:
      - labeled
jobs:
  clear-triage-label:
    if: github.event.label.name == 'next'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --remove-label triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
