name: Update roadmap issues
on:
  issues:
    types:
      - assigned
      - labeled
      - closed
      - deleted
  pull_request:
    types:
      - opened
      - closed
      - reopened
  workflow_dispatch:
  # We need to separately trigger when one of the other workflows completes
  # because GHA won't trigger another workflow based only on changes from
  # another workflow, such as updating labels.
  workflow_run:
    workflows:
      - Add triage label to new issues
      - Clear workflow labels once an issue is assigned
      - Clear triage label when moved to next
    types: [completed]
concurrency:
  group: ${{ github.ref }}-workflow-roadmap
  cancel-in-progress: true
jobs:
  update-dashboard-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: cashapp/activate-hermit@v1.1.3
      - run: update-dashboard-issue
        env:
          GH_TOKEN: ${{ secrets.FTL_WORKFLOW_TOKEN }}
          GH_REPO: ${{ github.repository }}
  update-roadmap-issues:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        label: ["jvm", "dx"] # add if desired: "codebase-health", "core", "infrastructure", "go", "security"
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: cashapp/activate-hermit@v1.1.3
      - run: |
          declare -A label_to_issue_map=(
            ["codebase-health"]=2443
            ["core"]=2442
            ["infrastructure"]=2441
            ["go"]=2440
            ["jvm"]=2439
            ["security"]=2438
            ["dx"]=2436
            ["python"]=3339
          )

          issue_number=${label_to_issue_map["${{ matrix.label }}"]}

          if [ -n "$issue_number" ]; then
            update-roadmap-issues "${{ matrix.label }}" "$issue_number"
          else
            echo "No associated issue found for label '${{ matrix.label }}'."
          fi
        env:
          GH_TOKEN: ${{ secrets.FTL_WORKFLOW_TOKEN }}
          GH_REPO: ${{ github.repository }}