# This name needs to be kept in sync with the workflow_run event in workflow-roadmap.yml
name: Clear workflow labels once an issue is assigned
on:
  issues:
    types:
      - assigned
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --remove-label triage --remove-label next
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
