# This name needs to be kept in sync with the workflow_run event in workflow-roadmap.yml
name: Add triage label to new issues
on:
  issues:
    types:
      - reopened
      - opened
      - unassigned
jobs:
  label-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh issue edit "$NUMBER" --add-label triage
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
